### PR TITLE
Redis Support for cBioPortal

### PR DESCRIPTION
**Pull request by averyniceday**
Added support for Redis (in addition to existing EhCache system)

- Properties changed to accept a base cache type
- Cache naming now depends on application/portal name
- System supports multiple apps sharing one redis instance for caching
- Updates to caching documentation

Here's a screenshot from grafana showing memory usage with traffic on genie deployed with redis. We can see that the memory usage plateaus at a relatively low level without stairstepping. This is because cached items are now stored on a separate node and redis instance (instead of in-memory like ehcache).

Screen Shot 2020-12-09 at 1 08 52 PM

Here's a screenshot without redis. 

Screen Shot 2020-12-08 at 7 04 04 AM

Related, we have created a new instance group for genie portal and redis to avoid issues where node is overloaded on memory due to multiple pods spiking on same node). Seperate PR will be created in the K8S repo. 

Squash during merge!! 

# Checks
- [ ] Runs on heroku
- [ ] Has tests or has a separate issue that describes the types of test that should be created. If no test is included it should explicitly be mentioned in the PR why there is no test.
- [ ] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [Giphy CAPTURE](https://giphy.com/apps/giphycapture) or [Peek](https://github.com/phw/peek)

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). It can help to figure out who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them either through slack or by assigning them as a reviewer on the PR

### CODE REVIEW

**Review by inodb — APPROVED** [review]
Thanks so much @averyniceday ! Great to see this come to fruition! Nice work!

Just for my understanding, both grafana images are for instances with cache enabled?

The top is using redis on separate nodes:

image

The bottom image is using ehcache:

image

Correct?

Second question is regarding the top image with redis on separate nodes. It seems like there is still a slight increase in memory over time? Def pretty minimal so it's prolly fine when there's more traffic as well but just curious if that's what you've observed

Last question is re performance differences. I know you previously benchmarked caching vs no caching but curious if the results are the same. Maybe just having a few stats of genie v8.1 study page time load with caching vs no caching. Could be nice to mention in the docs as well to have a few ballpark numbers

**Comment by averyniceday** [comment]
image

Leaving this here for now. We ran several tests using requests collected from the genie portal through hrrs and replayed them against our own test deployment without cache, with ehcache, and with redis. Redis performed similarly, if not slightly better than ehcache across most of the endpoints.

**Review by sheridancbio — APPROVED** [review]
This adds another option for persistence layer caching which is configured to run outside of the JVM. Hopefully this can help us with the memory resource / garbage collection issues we have been having in our backend clusters.

**Comment by averyniceday** [comment]
Forgot to open this as a draft PR first, but opened up another PR from same branch and the e2e localdb and travis tests passed. 

https://github.com/cBioPortal/cbioportal/pull/8261

Screen Shot 2021-01-08 at 12 48 57 PM

**Pull request merged**
