### PR TITLE
Stop import of mutation data on encountering unknown sample

### PR DESCRIPTION
**Pull request by j-hudecek**
Solves #772 
I've also removed an assert - by default asserts are not executed (you need to specify -ea) so an if is better

### CODE REVIEW

**Comment by jjgao** [comment]
@n1zea144 could you review this change?

**Comment by zheins** [comment]
Do we really want to stop importing on finding an unknown sample? @n1zea144 what do you think? My opinion is throw a warning and keep going if possible.

**Comment by jjgao** [comment]
@zheins @j-hudecek: it think it's a good idea to throw a warning.

**Comment by jjgao** [comment]
@n1zea144 @zheins let me know what you'd like to do with this? It's been there for too long.

**Pull request closed without merging**
