### PR TITLE
Mutation data counts

### PR DESCRIPTION
**Pull request by 7xuanlu**
PR for https://github.com/cBioPortal/cbioportal/issues/10357

1. Do mutation  data counts by gene specific

> Option 1: based on whether the sample is mutated or not
> Mutated (the samples with one or more mutations in the gene)
> Wild Type (the samples without mutations in the gene)
> NA (the samples that were not profiled)
> 
> Option 2: based on mutation type
> Missense Mutation, Frame Shift Del, Frame Shift Ins, etc...

2. Implement new MutationDataFilters to filter by above groups

### CODE REVIEW

**Comment by JREastonMarks** [comment]
Overall this looks like the PR would work, my big question is could any of these lambda function be more efficiently done with a new SQL query? It seems like we are doing a lot of work with the results.

**Comment by h164654156465** [comment]
> Overall this looks like the PR would work, my big question is could any of these lambda function be more efficiently done with a new SQL query? It seems like we are doing a lot of work with the results.

@JREastonMarks I've pushed some updates in https://github.com/cBioPortal/cbioportal/pull/10395/files#diff-afa1b11beff812038dd42375fe08a4d1990f7c5630d58e2d12a853dcb67b5d36. The refactor changes include moving java logic back to sql mapper, simplifying workloads in StudyViewController and StudyViewServiceImpl. Feel free to check it out. Let me know if anything missing! Thanks again for the suggestion.

**Comment by JREastonMarks** [comment]
@h164654156465 Just an FYI that we have repackaged our code base. You should be able to merge this branch into your code base without any difficulty.

Mostly this involved moving code around so:
model/src/main/java/org/cbioportal/model/GenomicDataCount.java
is now located here:
src/main/java/org/cbioportal/model/GenomicDataCount.java

**Comment by JREastonMarks** [comment]
Hi @7xuanlu ,
Can you update this with the new code in the master branch (6.0.0)? Afterwards I will be glad to review it again.

Thanks

**Comment by 7xuanlu** [comment]
> new code in the master branch (6.0.0)? Afterwards I will be glad to review it again.
> 
> Thanks

Hi @JREastonMarks , I've migrated this PR over to https://github.com/cBioPortal/cbioportal/pull/10559. Let's work from there, thanks!

**Pull request closed without merging**
