### PR TITLE
move treatments endpoint to internal API

### PR DESCRIPTION
**Pull request by jagnathan**
Move Treatments Endpoint to Internal API - fix  cBioPortal/icebox#561 

Note:
- API endpoints stay at the same location, just in certain clients they might have to refer to the endpoint now via internal instead of public

### CODE REVIEW

**Comment by jagnathan** [comment]
Move Treatments Endpoint to Internal API - fix #10345

**Comment by alisman** [comment]
@jagnathan is this ready for review?  This will probalby require a frontend change so lets be careful about that.

**Comment by jagnathan** [comment]
@alisman this is ready for review. as per my understanding, the frontend change is automatic. the API endpoint will move into internal section of the Swagger Doc. Are there other changes required on frontend?

**Review by inodb — APPROVED** [review]
LGTM ! Thank you!

**Pull request merged**
