### PR TITLE
Datasets API

### PR DESCRIPTION
**Pull request by JiaoJiao123**
# What? Why?
This API is designed for the [cBioPortal DataSets page](http://www.cbioportal.org/data_sets.jsp).

The current dataset page is served in the jsp file. We refactored this page under the cBioPortal front end structure. In the new file, we want to retrieve datasets info through API directly instead of through java code, and that's why we are developing this API.

Changes proposed in this pull request:
- get public datasets info
- corresponding unit test

# Notify reviewers
@cBioPortal/backend

### CODE REVIEW

**Comment by ersinciftci** [comment]
Isn't list of datasets actually list of cancer studies with a little bit more information? If that's the case, I think it's a good candidate for Study API's DETAILED projection instead of creating a new API.

**Comment by ecerami** [comment]
I agree with @ersinciftci's assessment.  We also discussed with @sheridancbio, @jjgao and Ben at last week's #mini-moonshot call.  Can we not proceed with this pull-request, and roll into the existing API instead?

**Comment by jjgao** [comment]
@JiaoJiao123 let's define an API that can accommodate both the Data Sets page and the query page. could you work with @ersinciftci, @sheridancbio and @andy?

**Comment by ersinciftci** [comment]
@JiaoJiao123 Since query page needs less data, it should suffice to call `SUMMARY` projection, and `DETAILED` projection should return the extra fields for data sets page. In order to do that, you need to move `sampleCount` property to `SUMMARY` projection (it's currently in `DETAILED`), and add the data sets related extra properties and joins to the `DETAILED` projection. You can always ping me on slack if you have questions/need help.

**Comment by ersinciftci** [comment]
@jjgao @sheridancbio and in the long term we can create columns for all those values in cancer_study table and precompute the data during import, so no calculation and join needed while retrieving data.

**Comment by ersinciftci** [comment]
Actually I just realized it won't make much difference since the result will be cached after the first call anyway.

**Comment by n1zea144** [comment]
On a related note, we have plans to do away with case lists altogether.  The case list and its corresponding size can be computed/cached at runtime.

**Comment by JiaoJiao123** [comment]
@ersinciftci @jjgao I didn't know the new Study API end point has already been implemented. I just checked it out and it is really nice! I really like the projection option. I would look into it more and see how to add the extra info for datasets page, will keep you updated.

**Comment by sheridancbio** [comment]
I'm also sorry I did not communicate with you yesterday. I'm glad we think we can accommodate the needs of both pages with the single endpoint. I hope I can help with the adjustments to the study projections.

**Pull request closed without merging**
