### PR TITLE
outlier bug fix

### PR DESCRIPTION
**Pull request by JiaoJiao123**
Bar chart outlier issues #1622

### CODE REVIEW

**Comment by zhx828** [comment]
Please see screenshot study: hnsc_tcga
screen shot 2016-09-03 at 1 47 53 pm

**Comment by zhx828** [comment]
Why show >2 if there is no case fall into this category? study: hnsc_tcga
screen shot 2016-09-03 at 1 49 16 pm

**Comment by zhx828** [comment]
There is a potential issue about this bar chart. Please see screenshot, we probably need to find a way either remove NA or use log scale for y-axis. @jjgao what do you think? This is from mskimpact study.

screen shot 2016-09-03 at 9 10 03 pm

**Comment by jjgao** [comment]
@zhx828 it is a good idea to provide an option to remove NA columns. Supporting log scale of y-axis for all bar chart is also a good idea. Another option would be supporting truncated y-axis.

**Comment by JiaoJiao123** [comment]
@zhx828 remember the discussion we had earlier? if we want to make >max and NA optional, we have to loop through data twice. then we decided keep both of them.

**Comment by zhx828** [comment]
@JiaoJiao123 no need to fix in this pull request. We should add this feature in iViz instead. I will add an issue to keep tracking of this idea.

**Comment by zhx828** [comment]
screen shot 2016-09-12 at 11 20 06 am
 study: hnsc_tcga

**Pull request closed without merging**
