### PR TITLE
Issue402 Issue438

### PR DESCRIPTION
**Pull request by aderidder**
Solves issue #402 
Added extra slider
Updated the labels for the sliders
Added a style for the tabs

Solves issue #438 
Added sorting for cancer type and detailed cancer type

Both are also on our test server

### CODE REVIEW

**Comment by ecerami** [comment]
thanks @aderidder.  this is great.

**Comment by ecerami** [comment]
Just tested this w/i the RC branch.  Looks good.

**Comment by ecerami** [comment]
Can we please merge this into the hotfix branch?  thanks.

cc' @priti88 so she knows when to redeploy on our end.

**Comment by jjgao** [comment]
@ecerami this is already merged.

**Comment by ecerami** [comment]
thanks @jjgao

**Pull request merged**
