### PR TITLE
Issue #510

### PR DESCRIPTION
**Pull request by zheins**
@zhx828 Will removing this overflow style be ok? I don't notice any problems taking it out.

### CODE REVIEW

**Comment by zhx828** [comment]
@zheins I think so. Only dynamicQuery is using this style, if you tested it already, it's ready to merge

**Comment by jjgao** [comment]
It was related to PR https://github.com/cBioPortal/cbioportal/pull/370. I'd ask @aderidder to review it.

**Comment by aderidder** [comment]
Hi,
I think you'll have to remove the overflow hidden from the tabs div of visualize.jsp as well. I did indeed add those overflow hiddens to solve the white-space problem, but the content of the dropdown now overflows the element's boundaries and as an effect is also hidden.
I removed both overflow hiddens on my local instance and it restored the dropdown functionality. Oddly, the white-space did not reappear; not sure why. If in your case it does reappear, maybe we could try to set the overflow hidden at a lower element, clear the floats some other way or add the dropdown at a different level.

**Comment by zheins** [comment]
@aderidder I think the overflow style in visualize.jsp was already removed. 

What was the original whitespace issue? I don't see a screenshot or good description of it in the previous merge.

**Comment by ecerami** [comment]
@zheins:  in the original whitespace bug, the query results page had two screenfulls of blank, gray area.  So, the screenshot would be a big gray rectangle at the bottom of the page.

**Comment by zheins** [comment]
I think for the moment, removing this styling makes sense. It's better to have whitespace than not be able to select items from the dropdowns.

**Comment by aderidder** [comment]
Yes I agree. Also, the white-space bug was extremely small on the main page.

2015-11-18 17:39 GMT+01:00 Zachary Heins <notifications@github.com>:

> I think for the moment, removing this styling makes sense. It's better to
> have whitespace than not be able to select items from the dropdowns.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cBioPortal/cbioportal/pull/511#issuecomment-157771300>
> .
>



-- 
E.   sander@thehyve.nl
T.   +31(0)30 700 9713
W.  www.thehyve.nl

the hyve

**Pull request merged**
