### PR TITLE
Fix for timeline data #1227 (but pointing to rc-dfci branch)

### PR DESCRIPTION
**Pull request by pieterlukasse**
Fix for timeline data #1227  (same as #1230, but pointing to rc-dfci branch)

The following needs to be changed in timeline files:
* change genetic_alteration_type to CLINICAL
* STOP_DATE is now a mandatory column (third column). The values should be blank when STOP_DATE is not used.

### CODE REVIEW

**Comment by jjgao** [comment]
@pieterlukasse will this also be needed for rc branch later? rc-for-dfci was a hack. We need to make sure anything merged to that branch will be merged to rc as well because we are going to delete that branch after rc is released.

**Comment by pieterlukasse** [comment]
@jjgao : yes, thanks for checking. All PRs to this branch are also made to `rc` . This one you can find in #1230 btw

**Comment by jjgao** [comment]
@pieterlukasse: OK. Is this ready to merge?

**Comment by pieterlukasse** [comment]
@jjgao : the idea is that @priti88 will test this first. Once she confirms this works, then we could merge. But we can merge first and patch later if necessary as well.

**Comment by priti88** [comment]
@pieterlukasse : fix works. Thanks

**Pull request merged**
