### PR TITLE
Fix patient mixed data; fix for MySQLbulkLoader to fix related unit test

### PR DESCRIPTION
**Pull request by pieterlukasse**
Fix to make the code more tolerant for a previously existing sample (instead of giving an error) for MIXED data type. 

A MySQLbulkLoader fix (discussed in #844) was also necessary to fix the related unit tests in `TestImportClinicalData`

### CODE REVIEW

**Comment by pieterlukasse** [comment]
@n1zea144 , @zheins : can you test this one for your clinical data? 

@morungos : this PR also includes the fix you need. I think I got the same errors you reported before while running the unit tests for this class, and with the changes in MySQLbulkLoader  these are now gone. Can you please review and check if it solves your problem as well?

**Comment by morungos** [comment]
There are still a few test issues here, certainly it doesn't yet run clean for me. It's still calling `System.exit()` somewhere. However, I think that the errors reported are actually there, and the stream closed stuff has all gone, so we can focus on the errors themselves.

**Comment by pieterlukasse** [comment]
@morungos : great, thanks for testing. The system.exit() issues are being solved in @fedde-s 's PR #1224 (it contains some of the classes, I expect he will add the remaining refactored classes to this PR)

**Comment by zheins** [comment]
@pieterlukasse - this fixes one of the issues we talked about. I still get this error:

ABORTED! Error:  No data was added.  Please check your file format and try again.

The import code incorrectly counts data added by counting the number of samples added to the database. If no samples are added, it assumes no data was added.

**Comment by pieterlukasse** [comment]
@zheins : thanks for testing. The error you mention should not occur any more unless  `numSamplesProcessed` counter is 0 at the end.... can you check why this is the case when processing your data? I think we are missing a use case here.

**Comment by pieterlukasse** [comment]
The error message is misleading btw...it is not counting the number of samples added, but the number of samples processed now...so 0 would be a strange result indeed. Something wrong with the data?

**Comment by zheins** [comment]
The exception thrown is on line 594. It occurs because a patient specific supplemental file (which we are specifying as "MIXED_ATTRIBUTES" type because of backwards compatibility) is still getting checked for sample specific attributes added. I think we just need to exclude "MIXED_ATTRIBUTES" type files from this check.

**Comment by pieterlukasse** [comment]
@zheins : I divided the validation into a PATIENT/SAMPLE specific set of checks and one specific for MIXED data type regarding "No data added". See my last commit. Can you test this and check if all works fine now? I will run some tests on my side tomorrow when back in the office. Thanks.

**Comment by zheins** [comment]
I think this should be good now. I might have a few more data issues to look into, but I was able to get more than one clinical supplemental file to import. I'll look into it first thing in the morning to make sure there is nothing else we need to address.

**Pull request merged**
