### PR TITLE
508 compliance changes

### PR DESCRIPTION
**Pull request by aderidder**
More 508 compliance changes

### CODE REVIEW

**Comment by pieterlukasse** [comment]
nb: I temporarily reverted changes on mutationMapper.js given that the fix should bedone in the library itself in another repository (as indicated by @onursumer in https://github.com/cBioPortal/cbioportal/pull/1177#discussion_r63102706)

**Comment by jjgao** [comment]
@pieterlukasse could you create a pull request of 508 compliance to MutationMapper?

**Comment by pieterlukasse** [comment]
@jjgao : sure, I included @fedde-s to solve this.

@jjgao :  who can review this current PR? Can you help us to assign someone for review and merge?

**Comment by onursumer** [comment]
@pieterlukasse @fedde-s : I can help reviewing/merging this PR once it is completed in the mutation mapper repository.

**Comment by jjgao** [comment]
@pieterlukasse @fedde-s @onursumer what's the status of this?

**Comment by pieterlukasse** [comment]
we are picking this up soon. At the moment we are trying to disable as many parts as possible via `skin_` configurations in portal.properties so ensure we focus our efforts on the remaining parts of the application.

**Comment by jjgao** [comment]
Has the corresponding change also made in MutationMapper?

**Comment by fedde-s** [comment]
@jjgao not yet, it was removed from this PR but we have not yet made a PR to the MutationMapper project.

**Comment by pieterlukasse** [comment]
@jjgao : the other changes in this PR can be merged, right?

**Comment by jjgao** [comment]
ready to merge?

**Comment by fedde-s** [comment]
No, mutationMapperTemplates.html does indeed seem to be part of the Mutation Mapper project, not cBioPortal. I’ll remove it from this pull request.

**Comment by fedde-s** [comment]
@jjgao It is now.

**Comment by jjgao** [comment]
@fedde-s I missed this for the release. Could you send a pull request to hotfix and I'll schedule it for release very soon.

**Comment by fedde-s** [comment]
@jjgao: Will do, thanks!

**Pull request closed without merging**
