### PR TITLE
Point all ln? links to use new index.do

### PR DESCRIPTION
**Pull request by inodb**
Fix https://github.com/cBioPortal/cbioportal/issues/3979 (don't use crosscancer.do)

### CODE REVIEW

**Comment by kalletlak** [comment]
@inodb is there a possibility for sending a list of study ids instead of `all` to `crosscancer.do`?

**Comment by inodb** [comment]
@kalletlak could you elaborate? The goal is to not use `crosscancer.do` anymore (we want to get rid of it). I'm sending a list of study ids in `cancer_study_list` and `cancer_study_id=all` to `index.do`

**Comment by kalletlak** [comment]
If someone already created `crosscancer.do` url with a subset of studies instead of `all`, should we support them

**Comment by inodb** [comment]
@kalletlak good point - we might want to do that. I think that is a different issue tho than redirecting ln? to index.do. That would be redirecting cross_cancer.do to index.do. Right?

**Comment by jjgao** [comment]
@inodb @kalletlak don't worry about crosscancer.do. I don't see much traffic pointing there now.

**Pull request merged**
