### PR TITLE
Add swagger api specification generation using springfox rc

### PR DESCRIPTION
**Pull request by sheridancbio**
Supersedes #909

### CODE REVIEW

**Comment by sheridancbio** [comment]
resolving conflicts

**Comment by sheridancbio** [comment]
Testing looks good overall after merging with the RC branch and resolving conflicts. However, I am getting the warning on the homepage : **The version of the portal is out of sync with the database!**

I suspect the error is due to me using a database which is not up to date, or not setting my portal.properties settings correctly. But please check this out before merging.

**Comment by sheridancbio** [comment]
I added this line to portal.properties, and it seems to have fixed the out of sync warning:
db.version=${db.version}

**Comment by n1zea144** [comment]
This looks good. I would just remove this file the following file as its contents have been rolled into the applicationContext-web.xml file:
web/src/main/resources/applicationContext-springfox.xml

**Comment by sheridancbio** [comment]
Dropped context file ... swagger-ui functions look to be working fine.

**Pull request merged**
