### PR TITLE
Further fix the build, enable travis

### PR DESCRIPTION
**Pull request by cataphract**
This builds on PR #104 (and consequently includes its commits).

It further fixes the build (see individual commits) and then enables building on travis. See an example of a build here: https://travis-ci.org/thehyve/cbioportal/builds/73377090

Note that merging this pull request is *not* enough to enable builds on travis. You also have to go to https://travis-ci.org and enable builds for the cBioPortal/cbioportal repository.

In total I had to mark 8 tests as failing. Four of them had been mentioned by @morungos but four other failures were being masked by calls to `System.exit()`.

### CODE REVIEW

**Comment by morungos** [comment]
Very well spotted on the `System.exit()`

**Comment by n1zea144** [comment]
Can we make another change:

business/src/main/resources/applicationContext-business.xml will need to be updated to inject the data source into JdbcUtil.java via org.springframework.beans.factory.config.MethodInvokingFactoryBean. One call should be added at the section at line 38 (used by our importer tool) and the other at line 53 ( when the code is running within tomcat).

**Comment by cataphract** [comment]
@n1zea144 Does it fix any of the tests now ignored? If so, you can send me a patch or push a branch somewhere and I'll add it to the pull request.

**Comment by n1zea144** [comment]
Its required based on changes that were made (injecting datasource into JdbcUtil.java) to enable the JUnit tests.  I can just add the changes when I merge the pull request.  Do you have any changes that are still pending or can I merge the pull request?

**Comment by cataphract** [comment]
You can go ahead. I've nothing else.

**Pull request merged**
