### PR TITLE
Delete unused ProteinArraySignificanceTest endpoint with security issue

### PR DESCRIPTION
**Pull request by adamabeshouse**
Fixes https://github.com/cBioPortal/cbioportal/issues/8680

### CODE REVIEW

**Review by sheridancbio — CHANGES_REQUESTED** [review]
If this servlet is being removed, I think we also need to drop the servlet beans from portal/src/main/webapp/WEB-INF/web.xml  (lines 341 - 348). Otherwise I expect we would see a BeanNotFound Exception during startup ... or maybe when the servlet is first accessed.

From the issue comments it seems like there is already approval to drop this service from the core. If that is so, this is a first step towards our larger cleanup (jettisoning the core).

**Comment by edvraa** [comment]
If I may suggest. Keep the class. Make `processRequest` return empty result early if it is really not used. That would be the quickest less intrusive security fix without making too much refactoring.

**Review by n1zea144 — APPROVED** [review]

**Comment by n1zea144** [comment]
@adamabeshouse Why not just include the update to web.xml as Rob suggests?  Seems like an easy update to the PR.

**Comment by adamabeshouse** [comment]
@n1zea144 @sheridancbio done! thanks

**Review by n1zea144 — APPROVED** [review]

**Pull request merged**
