### PR TITLE
Update Biojava dependency version to 4.2.0, fixes #1038

### LINKED ISSUE #1038: biojava dependencies error
Hi, I am getting error on Biojava dependencies below, when building core. 

Biojava site claims that http://biojava.org/wikis/BioJava:GetStarted/

BioJava, as of release 4.0.0 is available through Maven Central. or

You can get the latest version of BioJava3+ from the download page BioJava (v) (requires Java 1.6+).
(link to download is not working)

[ERROR] Failed to execute goal on project core: Could not resolve dependencies for project org.mskcc.cbio:core:jar:1.1.0: The following artifacts could not be resolved: org.biojava:biojava3-core:jar:3.0.7, org.biojava:biojava3-structure:jar:3.0.7: Failure to find org.biojava:biojava3-core:jar:3.0.7 in http://www.biojava.org/download/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of biojava-maven-repo has elapsed or updates are forced

### PR DESCRIPTION
**Pull request by heuermh**
The Biojava maven repository is currently unavailable, leading
to artifact resolution errors. This commit removes the repository
declaration and updates biojava-core and biojava-structure versions
to 4.2.0, the latest 4.x releases available in the Maven Central Repository.

As version 4.2.0 is binary incompatible with 3.x, dependency package
names were also updated.

Sorry, I've been away from this project for too long, so I'm not sure how to deploy
and test the modified code.

### CODE REVIEW

**Comment by heuermh** [comment]
Sorry, maybe I should have done a rebase?

**Comment by jjgao** [comment]
That'd be helpful :)

**Comment by heuermh** [comment]
Tried the brand new Github Update Branch button.  Or at least new to me.  Looks like it did a merge commit.  Give me a minute, when I get off-script with git I tend to get lost.  :)

**Comment by heuermh** [comment]
I did
```bash
$ git clone https://github.com/heuermh/cbioportal.git
$ git checkout biojava-4x
$ git remote add upstream https://github.com/cBioPortal/cbioportal.git
$ git fetch upstream
$ git rebase -i upstream/hotfix
```
and then it shows me two commits
```
pick b76742e Fallback when OpenID attribute exchange fails use identity
pick a845426 Update Biojava dependency version to 4.2.0, fixes #1038

# Rebase 16a6b96..21927de onto 16a6b96 (2 command(s))
```
That's not what I want, right?  Do I need to pull upstream/hotfix?

**Comment by inodb** [comment]
@heuermh thanks for fixing! I think it gets a bit obfuscated because hotfix is behind master but also has new commits, so if you rebase on hotfix I'm not exactly sure what happens. A simple solution might be to create a new branch off of hotfix and [cherry pick](https://ariejan.net/2010/06/10/cherry-picking-specific-commits-from-another-branch/) the one commit you want to add from your old branch. I can also clean it up and open a new PR if preferred

**Comment by inodb** [comment]
Just made this one https://github.com/cBioPortal/cbioportal/pull/1066

**Pull request closed without merging**
