### PR TITLE
Set the width of the Annotation column in cross-cancer queries to 100px

### LINKED ISSUE #2205: CIViC icon is not aligned with others under crosscancer page annotation column
I generated the screenshot by selecting all studies and querying for BRAF
screen shot 2017-03-10 at 4 12 31 pm

### PR DESCRIPTION
**Pull request by oplantalech**
# What? Why?
Fix #2205 by fixing the width of the Annotation column.

### CODE REVIEW

**Comment by oplantalech** [comment]
@zhx828 please, check if your issue is solved.

**Comment by zhx828** [comment]
@oplantalech I'm pretty sure this will solve the issue, but not really sure this is a proper solution though. @jjgao this could be an issue in the future if we add more annotation items.

**Comment by Sjoerd-van-Hagen** [comment]
@zhx828 Can you elaborate a bit? How would you like @oplantalech to resolve this issue?

**Comment by zhx828** [comment]
@Sjoerd-van-Hagen @oplantalech just spoke with JJ, this solution is ok.

**Comment by Sjoerd-van-Hagen** [comment]
@zhx828 Thanks Hongxin.
@jjgao Could you merge this PR?

**Pull request merged**
