### PR TITLE
Issue #938

### PR DESCRIPTION
**Pull request by zheins**
Filter at runtime spring config files

Add filtering of portal.properties for core module

Search order for spring context is $PORTAL_HOME/.. then classpath:...

Removed $PORTAL_HOME from poms

Put spring security intercepts directly into applicationcontext-security to simplify filtering.

### CODE REVIEW

**Comment by n1zea144** [comment]
Lets get rid of references to PORTAL_HOME/src/main resources in spring context files.

**Comment by inodb** [comment]
This seems to have broken travis: https://travis-ci.org/cBioPortal/cbioportal/builds/120946584

**Comment by inodb** [comment]
This should fix it: https://github.com/cBioPortal/cbioportal/pull/1016

**Comment by n1zea144** [comment]
Yes, the file no longer has to be copied.

**Pull request merged**
