### PR TITLE
Use EFDT library for Mutated Gene and CNA tables; Update EFDT library

### PR DESCRIPTION
**Pull request by zhx828**
EFDT: [Enhanced Fixed Data Table](https://github.com/cBioPortal/enhanced-fixed-datatable)

This related to #1002, #850,

### CODE REVIEW

**Comment by zhx828** [comment]
@jjgao @pieterlukasse The first version of EFDT(Enhanced-fixed-data-table) replacement has been finished in study view for all dataTables in summary tab. I will keep testing, at the mean time, since you are familiar with Study View, could you please also help me do some more testings? I may also need you help me to do the code review after testing, I will leave another comment or send an email to you. Thank you so much. We are on the way to the faster Study View. :)

**Comment by zhx828** [comment]
Please edit this comment to record all bugs/issues you may find.
- [ ] Item 1

**Comment by zhx828** [comment]
I think this is related to iViz as well. Could you take a look when you have time? Just the black box testing. @yichaoS @kalletlak

**Comment by jjgao** [comment]
Is the Travis problem because of the screenshot difference?

**Comment by zhx828** [comment]
@jjgao nope, phantomJS doesn't support HTML5 functions which ReactJS is highly relying on. Ino started a new process to solve this issue #1171

**Comment by aderidder** [comment]
@zhx828 nice! I've played around with it a bit and the speed is great! I've added two issues to your list.

**Comment by zhx828** [comment]
@aderidder Thank you! I will make these changes ASAP.

**Pull request merged**
