### PR TITLE
Removed an unused class

### PR DESCRIPTION
**Pull request by lemccarthy**
Removes the GenePanelMultipleStudyFilter class as it no longer has a purpose.

### CODE REVIEW

**Comment by jjgao** [comment]
@lemccarthy what are we going to do with this?

**Comment by lemccarthy** [comment]
@jjgao I could never get this to pass CI, Ersin could not figure it out either. I would argue that the class is useless, but removing it breaks something that I can't diagnose.

**Comment by jjgao** [comment]
@lemccarthy thanks for responding! :)

@n1zea144 do you think we should look into this?

**Comment by n1zea144** [comment]
@lemccarthy @jjgao I just looked into the issue.  Whats causing this AssertionError:

> fetchGenePanelData(org.cbioportal.web.GenePanelControllerTest)  Time elapsed: 0.015 sec  <<< FAILURE!
> java.lang.AssertionError: Status expected:<200> but was:<400>

is this line in  [InvolvedCancerStudyExtractorInterceptor.java](https://github.com/cBioPortal/cbioportal/blob/bfbeffa01e150ed565120a9371ed89fc187a871b/web/src/main/java/org/cbioportal/web/util/InvolvedCancerStudyExtractorInterceptor.java#L289) introduced in this PR:

`
List<SampleMolecularIdentifier> sampleMolecularIdentifiers = objectMapper.readValue(request.getReader(), List.class);
`

Jackson doesn't have enough information (class type) to know how to deserialize the data in the request into the list.  If you change it to the following, it will work:

`
List<SampleMolecularIdentifier> sampleMolecularIdentifiers = Arrays.asList(objectMapper.readValue(request.getReader(), SampleMolecularIdentifier[].class));
`

**Comment by jjgao** [comment]
I just modified @lemccarthy's code, but now we need to solve the conflicts. @n1zea144 could you help?

**Pull request merged**
