### PR TITLE
News for 3.1.6

### PR DESCRIPTION
**Pull request by jjgao**
news

Describe changes proposed in this pull request:
- news for 3.1.6

# Checks
- [ ] Runs on heroku
- [ ] Has tests or has a separate issue that describes the types of test that should be created. If no test is included it should explicitly be mentioned in the PR why there is no test.
- [ ] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!

# Any screenshots or GIFs?
NA

# Notify reviewers
NA

### CODE REVIEW

**Comment by inodb** [comment]
@jjgao thanks for adding this! Good idea to also add a news item for smaller releases

**Comment by jjgao** [comment]
@inodb thanks. Wondering if we can automate this...

**Comment by inodb** [comment]
@jjgao maybe if we pull just the items in the feature section, or anything with a news label or something. Not sure how to do the image part, but we could potentially scrape the whole description of the PR including figures

**Comment by jjgao** [comment]
@inodb I like the idea of adding a news label. Maybe automatically generate a news PR and then we can manually add screenshots?

**Pull request merged**
