### PR TITLE
Hotfix: update EFDT library and fix Study view issues

### LINKED ISSUE #1326: Selected filters not show properly when toggling chart from pie to table view in study-view

### LINKED ISSUE #1331: slider filter not reset in clinical data table
When clicking "Reset" link to reset the filters, text filters are reset/emptied but the slider (numeric) filters are not reset visually. See screenshot of the slider after reset (last column):

image

### PR DESCRIPTION
**Pull request by zhx828**
# What? Why?
Fix #1326, #1329, #1330, #1331, #1338, #1342, #1350, #1351.

Changes proposed in this pull request: 
- Update EnhancedFixedDataTable
- Apply bootstrap button styles to 'Clear All' Button in study view breadcrumb

# Checks
- [ ] Runs on Heroku.
- [x] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [x] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

# Any screenshots or GIFs?
No

# Notify reviewers
@pieterlukasse @kalletlak @yichaoS

### CODE REVIEW

**Comment by pieterlukasse** [comment]
@zhx828 : thanks for the fixes. I tested #1331 and it works :+1:  I also tested #1330 and now there is a tooltip, which is also an improvement :+1:   
I will close these 2 tickets now.

**Comment by zhx828** [comment]
@kalletlak found an issue #1342 Pull request is on hold until this error has been solved.

**Comment by zhx828** [comment]
@pieterlukasse Could you take a look commit https://github.com/cBioPortal/cbioportal/pull/1333/commits/c4b6e00c764bad3a0fb04aa9042aaf4c3aa2a7d4 ? Thank you.

**Comment by zhx828** [comment]
@pieterlukasse @kalletlak @yichaoS The pull request is ready to review, could you please help me take a look the issues you are interested? I also pinned you in some issue tickets you may be related. Let me know if you find any issues or have any questions. Thanks again.

**Comment by kalletlak** [comment]
Still getting #1342. Do not merge.

**Comment by zhx828** [comment]
The question above has been solved. If there are no other comments, I think the pull is ready to be merged.

**Comment by fedde-s** [comment]
The added tooltip (`title=` attribute) for the checkboxes in the tables of copy number-altered and mutated genes stops automated accessibility scans from complaining, but would it be feasible to make it descriptive of what the checkboxes are for? I think that would really help. Something like ‘Select <number> samples with this alteration’, I imagine.

**Comment by zhx828** [comment]
I'm going to do in this way. What do you think? @fedde-s @pieterlukasse 
508-title-study-view

**Comment by fedde-s** [comment]
@zhx828: great! Only for the mutated gene table, it may be even clearer to make it ‘Select 35 samples with MUC5B mutations’. In the CNA table you’ve basically already done this by listing in what way the gene was altered (amplification).

**Comment by jjgao** [comment]
@zhx828 what's the status of this PR?

**Comment by zhx828** [comment]
@jjgao this is done. Waiting the Travis

**Pull request merged**
