### PR TITLE
Query bug in study page

### PR DESCRIPTION
**Pull request by JiaoJiao123**
The previous hidden input were not removed before we append new ones to the submitted form. That's why it always query on the old gene input.

### CODE REVIEW

**Comment by JiaoJiao123** [comment]
Related to Issue #1480 Querying for genes in study view is broken

**Comment by JiaoJiao123** [comment]
@fedde-s  It will query based on current gene input now. And could you help with code review and testing?

**Comment by pieterlukasse** [comment]
@JiaoJiao123 : I tested it here and could not reproduce the problem on hotfix. This means I also cannot check if it works. I tested in Linux/Chrome, Linux/Firefox, Windows/Edge... all on hotfix branch (so not your fix). 

I noticed that other things fail though, like: 
- I cannot open the study view again after doing this query once
- The oncoprint seems to fail in Edge and I only see "Loading...." 
   - after running a second time I get a HTTP 500 with java.lang.OutOfMemoryError: Java heap space, around QueryBuilder.java:row 434

So these are my findings for now. At the moment @fedde-s and I are quite busy with some other topics. Could you maybe consider these findings and ask @zhx828 to review your code and perhaps @adamabeshouse to check why this QueryBuilder step is taking so much memory now?

**Comment by JiaoJiao123** [comment]
@pieterlukasse: hum that's very interesting. I just build a portal instance from hotfix branch and it still has this problem. Same with the query bug in http://www.cbioportal.org/  

Thank you very much for pointing out the other issues, but sorry I didn't see them from hotfix branch. I will work on them if I reproduce them later. 

And hongxin @zhx828 will help with code review and testing.

**Comment by zhx828** [comment]
Code looks good to me.

**Pull request merged**
