### PR TITLE
fixed #799

### LINKED ISSUE #799: Ambiguous Hugo gene symbols in `gene` table
A few (~43 of the ~58,000) of the hugo gene symbols found in the `gene` table actually map to 2 or more Entrez_gene_id values. See:

```sql
SELECT 
 HUGO_GENE_SYMBOL, 
 count(*) nr_entrez_gene_ids, 
 GROUP_CONCAT(ENTREZ_GENE_ID) as entrez_gene_ids 
FROM cbioportal.gene
group by HUGO_GENE_SYMBOL
order by count(*) desc
```
**Shouldn't we have 1 hugo mapping to 1 entrez?**

I checked a few of the results from the query above and noticed that the extra entrez items refer to other (sub)species, i.e. not *Homo sapiens (human)*. E.g.

Hugo: 'TRNL', has 4 Entrez Ids: '8923214,8923186,6775086,6775067'
When I check these on http://www.ncbi.nlm.nih.gov/gene/, I get:
Gene ID: 8923214, updated on 27-Nov-2012  
trnL [ Homo sapiens ssp. Denisova (Denisova hominin) ]
Gene ID: 8923186, updated on 27-Nov-2012
trnL [ Homo sapiens ssp. Denisova (Denisova hominin) ]
Gene ID: 6775086, updated on 10-Oct-2014
trnL [ Homo sapiens neanderthalensis (Neandertal) ]
Gene ID: 6775067, updated on 10-Oct-2014
trnL [ Homo sapiens neanderthalensis (Neandertal) ]

Hugo: 'ATP6', has 3 Entrez Ids: '8923188,4508,6775074'
When I check these on http://www.ncbi.nlm.nih.gov/gene/, I get:
Gene ID: 8923188, updated on 28-Oct-2015
ATP6 ATP synthase F0 subunit 6 [ Homo sapiens ssp. Denisova (Denisova hominin) ]
Gene ID: 4508, updated on 16-Jan-2016
MT-ATP6 mitochondrially encoded ATP synthase 6 [ Homo sapiens (human) ]
Gene ID: 6775074, updated on 26-Jun-2015
ATP6 ATP synthase F0 subunit 6 [ Homo sapiens neanderthalensis (Neandertal) ]

### PR DESCRIPTION
**Pull request by jjgao**
This pull request is to fix issue #799.

### CODE REVIEW

**Comment by jjgao** [comment]
@pieterlukasse could you help to review?

**Comment by pieterlukasse** [comment]
@jjgao : nice to see there is a class to import genes. Regarding microRNAs, maybe you should also update the class ImportMicroRNAIDs in a similar way?

**Comment by jjgao** [comment]
@pieterlukasse ImportMicroRNAIDs is legacy code. We should remove it.

**Comment by jjgao** [comment]
@pieterlukasse: @sheridancbio is working on better support for miRNA.. we will update ImportMicroRNAIDs if necessary.

**Comment by pieterlukasse** [comment]
@jjgao : I meant the specific change where you read the symbol from column 10 instead of column 2. This same mistake (i.e. column 2) is done in ImportMicroRNAIDs.

**Comment by jjgao** [comment]
@pieterlukasse ImportMicroRNAIDs is using another file, not the NCBI gene file.

**Comment by pieterlukasse** [comment]
@jjgao : sorry, I realised this later. Indeed another file :)  Which file/service are you using by the way?

**Comment by jjgao** [comment]
@pieterlukasse: It's a checked in pre-cursor and mature miRNA ID mapping file. Rob is writing some script to generate that file automatically from mirbase.

**Comment by pieterlukasse** [comment]
@jjgao I would like to suggest we add the following constraint to DB to correctly reflect the fact that Hugo symbols should be unique. 
```sql
alter table 
 cbioportal.gene
 add
  UNIQUE KEY `UQ_HUGO_GENE_SYMBOL` (`HUGO_GENE_SYMBOL`) COMMENT 'Constraint to ensure we have unique hugo symbols';
```

**Comment by morungos** [comment]
Yes, the more constraints the better :-)

**Comment by pieterlukasse** [comment]
I tested importGenes.pl (as this is reported in as the "usage" string). In this commit you can find the changed I made to get it working: https://github.com/thehyve/cbioportal/commit/f444ca03c7ed45d424f8b49d0e6198d6bec27fff

One remark about the logging: I think it is confusing to see this message at the end:
```
63792 records inserted into gene_alias
59882 records inserted into gene
```
while in fact no records were inserted (all were already present in DB). Maybe this is another issue that needs to be logged in a new ticket?

**Comment by pieterlukasse** [comment]
@jjgao : I loaded the new NCBI file using the fixed gene importer and can confirm that hugo column is now unique. In fact, I successfully applied the UQ constraint (which I mentioned before) to my DB. Could you add this UQ constraint to this PR as well?

**Comment by pieterlukasse** [comment]
@jjgao : I see that my proposed fixes in previous comments were not taken up. Would you like me to send them via a separate PR?

**Pull request merged**
