### PR TITLE
OncoKB updates

### PR DESCRIPTION
**Pull request by zhx828**
* Change OncoKB column to annotation column
* Sort annotation column based on icon existence
* Overlap resistance and sensitivity treatment icons together
* Performance improvements
* Bug fixes

### CODE REVIEW

**Comment by zhx828** [comment]
I'm using mutation mapper for cross cancer page and cohort view, @onursumer could you help me review my code, especially the OncoKB connector? Thanks a lot.

**Comment by jjgao** [comment]
@onursumer @zhx828 what's the status of this pr?

**Comment by onursumer** [comment]
Tested locally. It is functional and ready to merge.

The code looks good in general, but the OncoKBConnector.js seems too big to me. It might be better to refactor it into multiple files/components.

**Comment by zhx828** [comment]
@jjgao @onursumer I created a new issue to track the refactoring process #620

**Pull request merged**
