### PR TITLE
Study view bug fixes; Enable rainbow survival 

### LINKED ISSUE #2291: Study view hangs with ldap authentication and no sequenced or cna case list
Study view hangs with ldap authentication and no sequenced or cna case list:
captura de pantalla 2017-04-05 a les 12 16 47

This happens because cBioPortal is trying to retrieve non-existing case lists (sequenced and/or cna), and a 403 error is returned. However, in a system with no authentication, non-existing case lists return an empty list: http://www.cbioportal.org/api/sample-lists/prad_mskcc_2014_dummy/sample-ids.

These calls are made because the study view always shows the pie charts for 'With mutation data' and 'With CNA data'. For example, if there are no samples with mutation data, the pie chart shows all samples with mutation data = NO. 

This issue is probably related with the PR #2138 that @mandawilson did.

### PR DESCRIPTION
**Pull request by zhx828**
# What? Why?
Fix #2291, related to #2247 and https://github.com/cBioPortal/iViz/issues/450

Changes proposed in this pull request:
- Fix issue that the study without certain sample list hanged due to authentication (API will return 403). Solution: Get sample lists first then decide which sample list should be queried
- Give `No data available` message when study contains clinical attributes meta related to survival plot, but without actual data. More details are here #2247
- Give message `Failed to load data, refresh the page may help` when the API calls of Mutated Gene table and CNA table failed
- Silent release rainbow survival since this is an old feature

# Checks
- [ ] Runs on Heroku.
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

# Any screenshots or GIFs?
Screenshot (Survival analysis based on ucec_tcga, Diagnosis Age):
screen shot 2017-03-21 at 10 12 24 pm

screen shot 2017-04-05 at 3 52 51 pm
screen shot 2017-04-05 at 3 52 54 pm

# Notify reviewers
No need to review. They have been reviewed by @yichaoS  @kalletlak and @adamabeshouse

### CODE REVIEW

**Comment by pieterlukasse** [comment]
@zhx828 thanks for quickly taking action here. I would like however to discuss the 403 issue in more detail. I think it needs fixing in the backend, and not only in the frontend. The real issue is that when one uses the API to request a non-existing sample list, e.g. http://www.cbioportal.org/api/sample-lists/prad_mskcc_2014_dummy/sample-ids, the result is an empty list, while the **same** request returns 403 when the portal is running with authentication and the user is already logged in. I think that in both cases the result should be 404 (and not 403) or an empty list. At least it should be consistent.  
Adding @ersinciftci @mandawilson to this discussion as well.

**Comment by oplantalech** [comment]
@zhx828 It would also be nice to include the key you have introduced in the survival plots in the 'Mutation count vs. CNA' plot.

**Comment by oplantalech** [comment]
@zhx828 While revising your fixes, I found a similar bug for 'Mutation count vs. CNA' plot: when there is no gene panel data, a 403 error is raised instead of returning an empty list. The plot in the study view hangs indefinitely.
captura de pantalla 2017-04-06 a les 14 01 05

**Comment by mandawilson** [comment]
The security on the API always returns a 403 error on an object that is not found.  Intentionally.  I do understand that others might not agree, and am fine with it being changed after the right people are notified of the consequences.  Note I have done a lot of work with PHI so I am probably approaching this overly cautiously.  Say I make the change proposed (returning a 404 when the object is not found), and then a user does the following (with this made up API):

http://site.com/api/STUDY_THAT_DOES_NOT_EXIST

And they get a 404.  Next time I do:

http://site.com/api/STUDY_THEY_ARE_NOT_ALLOWED_TO_SEE

And they get a 403 error.  Now my API has leaked information about a study that the user is not allowed to see (and some might encode a bit of information into the study name).  So now they know a study exists.  That probably doesn't matter.

But we are talking about having sample and patient level security.  So then someone can do:

http://site.com/api/STUDY_THEY_ARE_ALLOWED_TO_SEE/PATIENT_THEY_ARE_NOT_ALLOWED_TO_SEE

Or:

http://site.com/api/STUDY_THEY_ARE_ALLOWED_TO_SEE/SAMPLE_THEY_ARE_NOT_ALLOWED_TO_SEE

And they get 404 errors.  Again, we have leaked information.  Now the patient ids *should not* be identifying, and really how much information can you get from a non-identifying patient id and a sample name anyway?  But to me security on an object means you cannot learn anything about this object.  Including that it exists.  And I would insist that a decision to change that come from higher up than anyone on this thread.

**Comment by ersinciftci** [comment]
I agree with @mandawilson

**Comment by zhx828** [comment]
@oplantalech I fixed the issue in the latest commit. I also have an issue to keep tracking of the rest of error handling progress.(https://github.com/cBioPortal/iViz/issues/450) But the items haven't been finished should be separated into anther pull request since this is more urgent to merge.

**Comment by ersinciftci** [comment]
Created a PR https://github.com/cBioPortal/cbioportal/pull/2294 so that http://www.cbioportal.org/api/sample-lists/prad_mskcc_2014_dummy/sample-ids will return a 404 instead of empty list.

**Comment by ersinciftci** [comment]
I guess I need to change the frontend error handling code in the same PR, because the study view screenshot test is failing. Can you guide me what file to change @zhx828 ?

**Comment by zhx828** [comment]
I dont think you need to change anything. Once this pull request is merged,
you can do a rebase, the screenshot test will pass

**Comment by ersinciftci** [comment]
@zhx828 I was going to rebase but this PR is merged to hotfix, can we merge it to rc as well?

**Comment by zhx828** [comment]
@jjgao can we merge hotfix branch to rc branch?

**Pull request merged**
