### PR TITLE
Issues #482 and #474 are fixed. 

### PR DESCRIPTION
**Pull request by istemi-bahceci**

### CODE REVIEW

**Comment by jjgao** [comment]
As discussed on the mailing list, we are trying to do code review for every pull request.

@onursumer would you be willing to review this PR?

**Comment by onursumer** [comment]
The code looks good to me other than some indentation mismatches, which I believe is related to IDE code style settings. I think we should try to define and start using the same code template for different IDEs to avoid these kind of inconsistencies.

I also noticed some changes in the portal/src/main/webapp/css/global_portal.css file are mostly a single white-space change at the end of the line. This may also be an unintended IDE behavior.

I will build & test the PR soon, and let you know if I see any major problems.

**Comment by onursumer** [comment]
I am getting this error message in the console:
<b>Can not apply layout: No such layout `cose-bilkent` found; did you include its JS file?</b>

@istemi-bahceci, can you look into this? You might have forgotten to add the file to the git tracker. Please reassign the task to me when you are done, thanks!

**Comment by istemi-bahceci** [comment]
@onursumer Thanks for pointing out, it seems that i forgot to add the new file as you said. Sorry for the inconvenience.

**Comment by jjgao** [comment]
Thank you, @istemi-bahceci, @onursumer. Please label the pr "ready to merge" when it's ready.

**Pull request merged**
