### PR TITLE
Added first draft of software acknowledgements page

### PR DESCRIPTION
**Pull request by ecerami**
# Overview

First step in adding the software acknowledgements page. See #5667. 

- added docs/Software-Acknowledgments.md

# Any screenshots or GIFs?
* Not applicable

# Notify reviewers
@inodb can you please merge this in?  We can finalize the text later.  But, for now, we can use this as first draft needed by the front end.  Thanks!

### CODE REVIEW

**Comment by inodb** [comment]
Do have merge permissions? Feel free to merge if so

**Comment by inodb** [comment]
If you btw want to add it to docs.cbioportal.org you'll also have to add it to SUMMARY.md and README.md

**Comment by ecerami** [comment]
Thanks @inodb.  What's the file typo?  don't see it.

Yes, I can merge, but I don't trust myself and want to follow the process :-)

**Comment by inodb** [comment]
Acknowledgments.md -> Acknowledgements.md

**Comment by ecerami** [comment]
ah, I think both are actually correct.  See https://grammarist.com/spelling/acknowledgment-acknowledgement/

> Both acknowledgment and acknowledgement appear throughout the English-speaking world, but acknowledgment, without the middle e, is preferred in U.S. and Canadian English, while acknowledgement is preferred outside North America.

Which may explain that we come from different parts of the world :-)

**Comment by inodb** [comment]
Oh lol 👌haha

Re process: usually once approved and u have merge permissions it's fine to merge

**Comment by ecerami** [comment]
Thanks @inodb.  BTW:  you are working way too late ;-)

**Pull request merged**
