### PR TITLE
Remove log4j 1.x and upgrade to log4j 2.16

### PR DESCRIPTION
**Pull request by Luke-Sikina**
- We were still importing log4j 1 via log4j-to-slf4j
- Updated log4j-to-slf4j to 2.16
- Updated logging in core using this guide: https://logging.apache.org/log4j/2.x/manual/migration.html

Output from `mvn clean install dependency:tree -DskipTests | grep log4j`:

```
[INFO] +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.15.0:compile
[INFO] |  \- org.apache.logging.log4j:log4j-api:jar:2.15.0:compile
[INFO] |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.15.0:compile
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.15.0:compile
[INFO] |  \- org.apache.logging.log4j:log4j-api:jar:2.15.0:compile
[INFO] |  \- org.apache.logging.log4j:log4j-core:jar:2.15.0:compile
[INFO] |     \- org.apache.logging.log4j:log4j-api:jar:2.15.0:compile
[INFO] |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.15.0:compile
[INFO] |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.15.0:compile
[INFO] |  \- org.apache.logging.log4j:log4j-core:jar:2.15.0:compile
[INFO] |     \- org.apache.logging.log4j:log4j-api:jar:2.15.0:compile
```

### CODE REVIEW

**Comment by jagnathan** [comment]
Looks good. Built the branch locally.  Ran the command: jar tvf ./portal/target/cbioportal.war | grep log4j.

The result is:

   792 Tue Dec 14 12:47:10 EST 2021 WEB-INF/classes/log4j.properties
301804 Mon Dec 13 20:17:30 EST 2021 WEB-INF/lib/log4j-api-2.15.0.jar
 17796 Tue Dec 14 12:46:50 EST 2021 WEB-INF/lib/log4j-to-slf4j-2.15.0.jar
1789769 Mon Dec 13 20:17:30 EST 2021 WEB-INF/lib/log4j-core-2.15.0.jar

log4j-1.2.17.jar is removed in the war file.

**Review by jagnathan — APPROVED** [review]
Looks good. Tested after building locally.

**Review by inodb — COMMENTED** [review]
Looks like we have to upgrade to v2.16.0: https://github.com/advisories/GHSA-7rjr-3q55-vv33

**Comment by Luke-Sikina** [comment]
> Looks like we have to upgrade to v2.16.0: [GHSA-7rjr-3q55-vv33](https://github.com/advisories/GHSA-7rjr-3q55-vv33)

Good catch. Updated.

**Comment by inodb** [comment]
Looks like these tests are already failing in master

**Pull request merged**
