### PR TITLE
Cross cancer plots

### PR DESCRIPTION
**Pull request by yichaoS**
http://dashi-dev.cbio.mskcc.org:8080/cc-plots/

Also added in the issue tracker: https://github.com/cBioPortal/cbioportal/issues/420

### CODE REVIEW

**Comment by jjgao** [comment]
- [ ] use expression case list
- [ ] move log config to y axis
- [ ] move download buttons below legend
- [ ] remove both left menu sections
- [ ] scale to fit all studies in the window
- [ ] only use provisional studies for TCGA?
- [ ] should we remove esca and stad for now?

**Comment by zheins** [comment]
Expression tab - When downloading pdf, it might be nice to display some sort of notification to the user that the request is being processed - it takes a few seconds and feels like the page isn't responding. Not really necessary though, its usually pretty quick.

One of the checkboxes wraps down next to the graph 
screen shot 2015-12-03 at 11 05 59 am

Other than that, I think the code looks pretty good.

**Comment by jjgao** [comment]
@yichaoS could you merge the latest rc branch and resolve the conflicts?

**Comment by jjgao** [comment]
just to make a screenshot for the news page :)

cross cancer expression

**Comment by jjgao** [comment]
Created an issue to keep track: https://github.com/cBioPortal/cbioportal/issues/600

**Pull request merged**
