### PR TITLE
Update ER Diagram

### PR DESCRIPTION
**Pull request by Luke-Sikina**
# What? Why?
The ER diagrams found in db-scripts were out of date. This pull request updates them.

Changes proposed in this pull request:
- Deleted all old diagrams
- Created new ER diagram for 3.0.6
- Verified that documentation references the new diagram

# Checks
- [ ] Runs on Heroku.
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to master.
- [ ] If this is a bug fix, create a unit and/or e2e test, or explain why that cannnot be done.

# Any screenshots or GIFs?
See the committed files for before and after.

### CODE REVIEW

**Comment by jjgao** [comment]
The tables that are safe to be deleted are logged here: https://github.com/cBioPortal/cbioportal/pull/6584

We still need to keep `drug` and `text_cache` for the moment.

**Comment by pieterlukasse** [comment]
@jjgao that looks like a circular link...did you mean to refer to another ticket?

**Comment by jjgao** [comment]
@pieterlukasse sorry, fixed.

**Comment by pieterlukasse** [comment]
@Luke-Sikina can you update the diagram according to #2054? I.e. make a "deprecated" group and put the tables mentioned in #2054 there. Maybe make a separate group for "deprecation candidates" and add tables like `drug` and `text_cache` there. Also add `users` and `authorities` tables there. Once that's done we could merge this PR. The actual cleanup of the tables could be done in a next PR.

**Comment by Luke-Sikina** [comment]
Accidentally rebased master instead of rc and forced pushed.

**Pull request closed without merging**
