### PR TITLE
add backslashes to bash commands in docs/Import-Gene-Sets.md

### PR DESCRIPTION
**Pull request by messersc**
Signed-off-by: Clemens Messerschmidt <clemens.messerschmidt@charite.de>

# What? Why?
Fix missing backslashes in multi-line bash commands in docs/Import-Gene-Sets.md.

# Checks
- [ ] Runs on Heroku.
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [x] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [GifGrabber](http://www.gifgrabber.com/).

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). If you are part of the
cBioPortal organization, notify the approprate team (remove inappropriate):

@cBioPortal/frontend
@cBioPortal/backend
@cBioPortal/devops

If you are not part of the cBioPortal organization look at who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them here:

### CODE REVIEW

**Comment by messersc** [comment]
Hi @sandertan,

I guess you are the right person to review this.

Cheers,
Clemens

**Comment by sandertan** [comment]
Hi Clemens,

Thanks for catching this. Can you direct your pull request to the cBioPortal:hotfix branch?

I assume you are loading gene set data in cBioPortal. The backend works and is merged, but the UI for gene sets is not yet in the Master branch. Some refactoring is pending to make this merge possible. 

A fully functional version can be found in this branch: https://github.com/thehyve/cbioportal/tree/geneset_fixes

If you'd like to test the feature, you can try out our demo server here: https://cbioportal.thehyve.net/cbioportal/

Let me know if you have any questions 
Best,
Sander

**Comment by messersc** [comment]
Hi Sander,

I changed the branch to merge into to `hotfix`. (This created another commit? Could you squash them?)

I thought I needed this when importing `study_es_0`, but I ran into the errors with the database, so it was easier to just remove the last line from `data_fusions.txt`, which defined the gene set.

Still wanted to fix this in the docs.

Thanks for your help,
Clemens

**Comment by sandertan** [comment]
Hi Clemens

I can't push to your repository, so I can't squash them for you. In your local branch (with the 1 commit), can you do a `git pull --rebase upstream hotfix`? (Replace upstream with the name of the cBio repo). This will place the commit after the latest commit in hotfix. Then force push (git push -f) to your remote branch, and the PR will update itself.

I've been trying to streamline the process of loading `study_es_0` since the gene panel en gene set implementation. It should run fine when using the latest master branch (indeed with latest database as well). Let me know if you run in any more issues.

Thanks, 
Sander

**Pull request merged**
