### PR TITLE
Add DB property to enable/disable prepared statement pooling

### PR DESCRIPTION
**Pull request by ao508**
Make pooling prepared statements setting for db a portal property. 

Signed-off-by: Angelica Ochoa <15623749+ao508@users.noreply.github.com>

### CODE REVIEW

**Comment by ao508** [comment]
@sheridancbio resolved

**Comment by pieterlukasse** [comment]
just out of curiosity: is anyone deploying this set to `true`? This was the cause of the memory leak, right?

**Comment by inodb** [comment]
Yeah I think we should be very explicit here that it can only be enabled when running the importer. It might therefore be better to make it a command line parameter for the importer if possible instead

**Comment by pieterlukasse** [comment]
Given @inodb's comment, maybe we should close this PR to avoid confusion?

**Comment by sheridancbio** [comment]
Withdrawing request for review from @inodb with permission

**Comment by sheridancbio** [comment]
@inodb I believe this could already operate as a command-line parameter with the mechanism used by @ao508 ... so perhaps you are recommending that we drop the line from the portal.properties.EXAMPLE file and instead make it an undocumented property?
Or would you prefer that we add a comment above the portal.properties line saying "#caution: db.enable_pooling is intended to be used only for data-import - memory leaks are observed setting this property to true in cbioportal web applications" ?

**Comment by sheridancbio** [comment]
@inodb We have dropped the property from portal.properties. We decided this would be an undocumented feature used only for building an (network optimized) importer.

**Pull request merged**
