### PR TITLE
Restore zoom slider and dont save minimap open state

### PR DESCRIPTION
**Pull request by adamabeshouse**
Restore zoom slider controls
Always hide minimap by default
Hide unsightly whitespace while oncoprint loads

# Checks
- [ ] Runs on Heroku.
- [x] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [x] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [x] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [x] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

# Notify reviewers
@schultzn @jjgao

### CODE REVIEW

**Comment by jjgao** [comment]
Now the menu gets really long, it moves the oncoprint up and down. It also mess up with legend. Maybe we should not hide the menu any more. @schultzn

**Comment by schultzn** [comment]
It was always useful for quick screenshots to have the menu bar hidden.

Why do we use “Download” instead of the download icon we use elsewhere?

**Comment by jjgao** [comment]
@schultzn We changed everything to text for this menu. We could put some icon, e.g. download, to save some space, but it'll still be a problem when the screen is small.

@adamabeshouse in the current code, there is some space between "Altered in..." line and OncoPrint. Could you bring the space back? Ideally, show/hiding menu should not move the OncoPrint.

**Comment by adamabeshouse** [comment]
@jjgao @schultzn I think someone asked me once to put "Altered cases" close to the oncoprint - maybe I could put the toolbar above, and try to position it absolute so it doesnt shift things up and down?

**Comment by schultzn** [comment]
@adamabeshouse I think that is a good compromise.

**Pull request merged**
