### PR TITLE
Style idea

### PR DESCRIPTION
**Pull request by alisman**
# What? Why?
Fix # .

Changes proposed in this pull request:
- a
- b

# Checks
- [ ] Runs on Heroku.
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [GifGrabber](http://www.gifgrabber.com/).

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). If you are part of the
cBioPortal organization, notify the approprate team (remove inappropriate):

@cBioPortal/frontend
@cBioPortal/backend
@cBioPortal/devops

If you are not part of the cBioPortal organization look at who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them here:

### CODE REVIEW

**Comment by jjgao** [comment]
@brittanystoroz what do you think about Aaron's change?

image

**Comment by alisman** [comment]
@jjgao Ethan asked me to restore the header to last iteration and I'm happy to do that.   The reason the the header is left aligned here is that it should be for pages which are 100% width.   @brittanystoroz jjgao and I talked about maybe making the center content block left aligned on all pages.

**Comment by brittanystoroz** [comment]
@alisman @jjgao I'm not sure what this means: "The reason the the header is left aligned here is that it should be for pages which are 100% width."

I had the links aligned to the right so they could expand/collapse responsively based on screen width. Having them directly next to the logo makes the super wide width of the page content look a bit bizarre. I also think the gray background is a bit dark, but perhaps it's just my screen.

In general it would be nice to get this feedback while the PRs are opened. I previously tagged you in changes for the sidebar that went unanswered, so didn't rope you into the header changes, though I did receive and act on feedback from others. I'm happy to do the same with your feedback during the appropriate phase of iterations, but creating a new design and pull request immediately after the changes go live is incredibly overbearing and condescending.

**Comment by brittanystoroz** [comment]
I'm happy to discuss future iterations and changes for design work after things go live -- nothing will be perfect the first time around and design is a very iterative process. So nothing has to be set in stone, but I think in the future it might be best to bring up post-deployment feedback in an issue with a 'discussion' label so that it can be more of a continuous conversation rather than a pull request of new work. That way no one has to feel pressured to jump back to previous work and it won't disrespect anyone's time or effort.

**Comment by jjgao** [comment]
@brittanystoroz We all think you were doing a great job. Several users told me verbally that they really liked the new style after it's released. We really appreciate your work and hope you can lead/guide us to more improvement.

I don't think this pull request is by any means to force the change. It's more of a prototype (one option) for the next iteration. 

But I just realized the context has been lost in this PR -- sorry about that. This is meant to better support the new patient view page to be released soon.

http://www.cbioportal.org/beta/case.do#/patient?caseId=TCGA-BK-A0CC&studyId=ucec_tcga_pub

There are two main differences I can see in terms of styling in the new patient view:

1. We now have two header sections (site header and patient header) -- we may want to use (slightly) different styles/colors for them.
1. We are filling the whole page now.

And I think @alisman separated this piece of styling code he previous had for the new page and put it here for discussion.

**Pull request closed without merging**
