### PR TITLE
Encoding fix

### PR DESCRIPTION
**Pull request by aderidder**
As requested we've updated the pom in core to include the encoding
When we ran the tests, the TestPiHelperDrugImporter had an issue with the ´ character, so we changed it to ' 

Tests run: 210, Failures: 0, Errors: 0, Skipped: 14

### CODE REVIEW

**Comment by ecerami** [comment]
thanks a lot.  @jjgao can you merge in?  should this go into master, rc, or both?

**Comment by ecerami** [comment]
hey @jjgao:  can you actually hold off on merging this.  as it also fails, and Hyve group looking into this further.

**Comment by jjgao** [comment]
I think this could go to hotfix since it's a bug fix, and then merge to master and rc.

**Comment by jjgao** [comment]
It it weird that only pull requests break Travis.

For example, there was a pull request from Hongxin, which failed:

https://github.com/cBioPortal/cbioportal/pull/156
https://travis-ci.org/cBioPortal/cbioportal/builds/74307250

But after merging to pull request, the build passed:

https://travis-ci.org/cBioPortal/cbioportal/builds/74448765

I could not figure out a reason. If it is related to encoding, why the current rc and master pass the CI? What's the difference between a pull request and a push?

**Comment by ecerami** [comment]
Are we using environment variables within travis CI?  According to this:  http://docs.travis-ci.com/user/pull-requests/, environment variables are treated differently within pull requests.

**Comment by ecerami** [comment]
Closing this, because we have applied directly.

**Pull request closed without merging**
