### PR TITLE
Adding correct UQ constraint to gene table

### LINKED ISSUE #1266: Add missing UQ constraint to `gene` table
Add the constraint as discussed in #805 (see https://github.com/cBioPortal/cbioportal/pull/805#issuecomment-179274725 and https://github.com/cBioPortal/cbioportal/pull/805#issuecomment-180355753)

### PR DESCRIPTION
**Pull request by pieterlukasse**
# What? Why?

Fixes #1266, adding a unique constraint to the gene table. Replaces #1422. 

Changes proposed in this pull request:
- gene table gets a unique constraint to ensure we don't get wrong data

:warning: if the table gene already contains duplicated entries, the migration script will fail. The script contains some references to documentation on how to fix it in this case. 
# Notify reviewers

@sheridancbio  , @zheins, @jjgao

### CODE REVIEW

**Comment by zheins** [comment]
This looks good to me!

**Comment by sheridancbio** [comment]
I am testing this now .. I am thinking that once there is a unique key on a field, there is no need to have an additional "plain" key on the same field. I believe that a "UNIQUE KEY" and a "KEY" both create a B-Tree index on the column (or set of columns) which can be used for optimizing table operations (joins, sorts, ..)
If this is so, then maybe we should simply change this line:
KEY `HUGO_GENE_SYMBOL` (`HUGO_GENE_SYMBOL`)
to:
UNIQUE KEY `HUGO_GENE_SYMBOL` (`HUGO_GENE_SYMBOL`)
and use alter table to change the index to be a UNIQUE KEY (rather than adding a new one)

**Comment by sheridancbio** [comment]
Testing shows that an index created as UNIQUE KEY will function (for joins and selects) equivalently to an index created as KEY.
If it is ok, I recommend one key line in cgds:
UNIQUE KEY HUGO_GENE_SYMBOL ( HUGO_GENE_SYMBOL)
and in migration.sql:
ALTER TABLE gene DROP KEY `HUGO_GENE_SYMBOL`;
ALTER TABLE gene ADD UNIQUE KEY `HUGO_GENE_SYMBOL` (`HUGO_GENE_SYMBOL`);

On a separate issue .. I have discovered that some of the comments I put in to the sql scripts don't follow the correct mysql comment syntax (oops). The rule is that a line starts with two hyphens and then has a whitespace character. So maybe the change to migrate_db.py should look like:
        # skip blank lines
        if len(line.strip()) < 1:
            continue
        # skip comments
        if line.startswith('#') or (line.startswith('--') and line[2:3].isspace()):
            continue

otherwise, a line which is two hyphens followed by newline, or two hyphens followed by tab will not be skipped.

**Comment by sheridancbio** [comment]
I think (not yet discussed in Engineering Review meeting) that we are moving to a versioning approach where incompatible changes in schema increment the major version number, rc branch changes increment the middle number, and hotfix branch changes increment the third number.

Currently @angelicaochoa has a hotfix PR which incremented the version number to 1.3.2 in hotfix. If this PR is to go in before rc is merged to master, then the next number after @angelicaochoa 's pr would be 1.3.3. 

Also, the comment ignore fix was merged to rc in another PR, but could still be done here. When rc gets merged to master the conflict should be resolved to use just one branch.

But the basic question here is ... do we have redundant gene entries still in our gene table and will this hotfix change be a problem to merge or not?  I remember we identified a bunch of redundancies. I am not sure if we have addressed those yet.  If things are fixed now and this could go in without disruption then let's get it in sooner rather than later I think.

**Comment by sheridancbio** [comment]
I have just checked for duplicate records in our current largest production database. There are 43 such entries. Here they are:

mysql> select HUGO_GENE_SYMBOL, count(*), group_concat(entrez_gene_id)  from gene group by HUGO_GENE_SYMBOL having count(*) > 1 order by count(*) desc limit 43;
+------------------+----------+---------------------------------+
| HUGO_GENE_SYMBOL | count(*) | group_concat(entrez_gene_id)    |
+------------------+----------+---------------------------------+
| TRNL             |        4 | 6775067,6775086,8923186,8923214 |
| TRNS             |        4 | 6775068,6775080,8923189,8923207 |
| ATP6             |        3 | 4508,6775074,8923188            |
| ATP8             |        3 | 4509,6775077,8923211            |
| COX1             |        3 | 4512,6775083,8923218            |
| COX2             |        3 | 4513,6775079,8923202            |
| COX3             |        3 | 4514,6775073,8923187            |
| CYTB             |        3 | 4519,6775065,8923205            |
| ND1              |        3 | 4535,6775098,8923209            |
| ND2              |        3 | 4536,6775094,8923212            |
| ND3              |        3 | 4537,6775076,8923206            |
| ND4              |        3 | 4538,6775072,8923197            |
| ND4L             |        3 | 4539,6775071,8923201            |
| ND5              |        3 | 4540,6775066,8923210            |
| ND6              |        3 | 4541,6775063,8923198            |
| TRNA             |        3 | 4553,6775093,8923217            |
| TRNC             |        3 | 4511,6775084,8923200            |
| TRND             |        3 | 4555,6775081,8923215            |
| TRNE             |        3 | 4556,6775064,8923199            |
| TRNF             |        3 | 4558,6775088,8923184            |
| TRNG             |        3 | 4563,6775075,8923191            |
| TRNH             |        3 | 4564,6775069,8923196            |
| TRNI             |        3 | 4565,6775097,8923193            |
| TRNK             |        3 | 4566,6775078,8923190            |
| TRNM             |        3 | 4569,6775096,8923204            |
| TRNP             |        3 | 4571,6775089,8923216            |
| TRNQ             |        3 | 4572,6775095,8923208            |
| TRNR             |        3 | 4573,6775070,8923195            |
| TRNT             |        3 | 4576,6775062,8923192            |
| TRNV             |        3 | 4577,6775090,8923185            |
| TRNW             |        3 | 4578,6775092,8923194            |
| TRNY             |        3 | 4579,6775082,8923203            |
| 12S RRNA         |        2 | 6775087,8923213                 |
| 16S RRNA         |        2 | 6775085,8923219                 |
| HBD              |        2 | 3045,100187828                  |
| LSAMP-AS1        |        2 | 100506708,101926903             |
| MEMO1            |        2 | 7795,51072                      |
| MMD2             |        2 | 221938,100505381                |
| RNR1             |        2 | 4549,6052                       |
| RNR2             |        2 | 4550,6053                       |
| SFPQ             |        2 | 6421,654780                     |
| TEC              |        2 | 7006,100124696                  |
| TRNN             |        2 | 4570,6775091                    |
+------------------+----------+---------------------------------+
43 rows in set (0.10 sec)

**Comment by pieterlukasse** [comment]
@sheridancbio thanks for the update. Regarding the list you just shared, I have some questions/remarks:
- question: are you aware of the changes done here https://github.com/cBioPortal/cbioportal/pull/805/files#diff-1d070fc4f5adf0bc6c0ef20e7894cf07R77 ? Here we discovered that the DBs had been populated with the wrong column (column 3 while it should be column 11). When using this to populate `gene` table (as we do for the seed DBs), there should be no duplicated HUGO_GENE_SYMBOL values in the table.
- remark: when looking at the most recent NCBI Entrez file from ftp://ftp.ncbi.nih.gov/gene/DATA/GENE_INFO/Mammalia/Homo_sapiens.gene_info.gz (which we use to populate `gene` table), you will see that MMD2 only occurs once in column `Symbol_from_nomenclature_authority` (col 11). I expect the same to be true for all the other symbols you reported here.

**Comment by sheridancbio** [comment]
Thanks Pieter. I'll look at this. I know that @angelicaochoa implemented new code to pull genes from the NCBI file periodically. We should double check that the new code is using the correct column as well.

Maybe we can delete these ambiguous records. I think we should first check that none of the "bad" Entrez Gene Ids have genetic data / profiles / events. I guess we could adopt a policy (if it is not already the case) that we do not allow any entrez ids to be added to the gene table if the entrez record has no "Symbol_from_nomenclature_authority" value set. Then we would only have a problem if genetic data comes in for one of these entrez gene ids.

**Comment by pieterlukasse** [comment]
thanks @sheridancbio . I think that the entries without an official hugo symbol could still be added with their entrez id as their "symbol" for the time being. This solves the problem you mentioned in your last sentence.

**Comment by sheridancbio** [comment]
Update: I discussed this briefly with @angelicaochoa and @zheins a few days ago. The new gene table importer (Gene Data Update Tool) by @angelicaochoa does (when the nomencalture authority column is blank) fall back on using the other column:
<pre>
private final String SYMBOL_COLUMN = "Symbol";
private final String MAIN_SYMBOL_COLUMN = "Symbol_from_nomenclature_authority"
String hugoGeneSymbol = record.getProperty(MAIN_SYMBOL_COLUMN).equals("-") ? 
    record.getProperty(SYMBOL_COLUMN) :
    record.getProperty(MAIN_SYMBOL_COLUMN);
</pre>
You propose that for our database tables we instead use a different gene symbol for records that have a blank in the nomenclature authority column. We want to discuss this a little more. We want to find out whether we have any genetic profiling data for any of the 43 cases listed above (data for the entrez ids which have "-" in the nomenclature authority column). But we are also wondering what we would do if profiling data were to arrive for these genes later. If a user wants to query for the "other" MMD2, how would they do it? I guess that we cannot support that currently, since there is no disambiguation step to resolve *which* MMD2 records to retrieve. Maybe the lowest numbered entrez id would be found by default currently.

I think we would prefer to identify genes in the system primarily by entrez gene id. There will need to be a step of resolving a user query by hugo symbol to an entrez gene id. Maybe we should silently assume it is the entrez record marked as "from_nomenclature_authority", as this PR implies - that makes sense, but it does not allow access to the other entrez records which have the queried value in the "Symbol" column. Also, when a gene profile is displayed we need a proper display name for the gene. For genes like the "other" MMD2, should the oncoprint show "100505381" or maybe "MMD2(entrez:100505381)" or something else... we want to think a little more.

**Comment by sheridancbio** [comment]
I have done a search for any cna profile data involving the ambiguous hugo_gene_symbols.
<pre>
mysql> select distinct gene.entrez_gene_id, gene.hugo_gene_symbol from cna_event inner join gene on cna_event.entrez_gene_id = gene.entrez_gene_id where cna_event.ENTREZ_GENE_ID in (3045,4508,4509,4511,4512,4513,4514,4519,4535,4536,4537,4538,4539,4540,4541,4549,4550,4553,4555,4556,4558,4563,4564,4565,4566,4569,4570,4571,4572,4573,4576,4577,4578,4579,6052,6053,6421,7006,7795,51072,221938,654780,6775062,6775063,6775064,6775065,6775066,6775067,6775068,6775069,6775070,6775071,6775072,6775073,6775074,6775075,6775076,6775077,6775078,6775079,6775080,6775081,6775082,6775083,6775084,6775085,6775086,6775087,6775088,6775089,6775090,6775091,6775092,6775093,6775094,6775095,6775096,6775097,6775098,8923184,8923185,8923186,8923187,8923188,8923189,8923190,8923191,8923192,8923193,8923194,8923195,8923196,8923197,8923198,8923199,8923200,8923201,8923202,8923203,8923204,8923205,8923206,8923207,8923208,8923209,8923210,8923211,8923212,8923213,8923214,8923215,8923216,8923217,8923218,8923219,100124696,100187828,100505381,100506708,101926903);
+----------------+------------------+
| entrez_gene_id | hugo_gene_symbol |
+----------------+------------------+
|           3045 | HBD              |
|           4571 | TRNP             |
|           6421 | SFPQ             |
|           7006 | TEC              |
|           7795 | MEMO1            |
|          51072 | MEMO1            |
|         221938 | MMD2             |
|         654780 | SFPQ             |
|      100124696 | TEC              |
|      100187828 | HBD              |
|      100505381 | MMD2             |
|      100506708 | LSAMP-AS1        |
|      101926903 | LSAMP-AS1        |
+----------------+------------------+
13 rows in set (0.00 sec)
</pre>

There are three directly ambiguous cases in the cna_event data.
- There is a profile for entrez 7006, and for entrez 100124696 .. both having name "TEC".
- There is a profile for entrez 7795, and for entrez 51072 .. both having name "MEMO1".
- There is a profile for entrez 3045, and for entrez 100187828 .. both having name "HBD".

Also, there are these uncertain cases:
- entrez 654780 is for a gene who's symbol is now "LOC654780" on the ncbi gene website (not SFPQ). Perhaps this entrez id was chosen incorrectly during import? or maybe it is correctly the LOC654780 gene, but is incorrectly linked in our database to SFPQ (which is an alias for this gene).
- entrez 100505381 is for the gene with unofficial id "MMD2". Similar to the previous case, perhaps this entrez id was chosen incorrectly during import or perhaps it is correct and happen to not have any cna_events for the official MMD2 gene. Either way, something needs to be corrected here -- either shifting to the other entrez_gene_id, or altering things so that a query for MMD2 either does not show this profile or makes it clear to the user that this is actually "Miyoshi muscular dystrophy 2", and not "monocyte to macrophage differentiation associated 2"
- entrez 100506708 is marked as a discontinued gene on the ncbi website. It says it has been replaced with 101926903, so perhaps we need to update / merge these events into entrez id 101926903 ... and also scan for other events/profiles which use discontinued entrez gene ids.
- entrez 100187828 has gene symbol HBD on the ncbi website, but it is not official. Confusingly, there are two different entrez ids with an "official" gene symbol of HBD:
https://www.ncbi.nlm.nih.gov/gene/3045 (official by HGNC)
https://www.ncbi.nlm.nih.gov/gene/748577 (official by VGNC)
So for this gene symbol, there appear to be two entrez genes with an "official" gene symbol and one entrez gene with an un-official gene symbol of "HBD" I guess we could ignore VGNC.

**Comment by sheridancbio** [comment]
I have done a search for any mutation profile data involving ambiguous gene symbols.
<pre>
select distinct gene.entrez_gene_id, gene.hugo_gene_symbol from mutation_event inner join gene on mutation_event.entrez_gene_id = gene.entrez_gene_id where mutation_event.ENTREZ_GENE_ID in (3045,4508,4509,4511,4512,4513,4514,4519,4535,4536,4537,4538,4539,4540,4541,4549,4550,4553,4555,4556,4558,4563,4564,4565,4566,4569,4570,4571,4572,4573,4576,4577,4578,4579,6052,6053,6421,7006,7795,51072,221938,654780,6775062,6775063,6775064,6775065,6775066,6775067,6775068,6775069,6775070,6775071,6775072,6775073,6775074,6775075,6775076,6775077,6775078,6775079,6775080,6775081,6775082,6775083,6775084,6775085,6775086,6775087,6775088,6775089,6775090,6775091,6775092,6775093,6775094,6775095,6775096,6775097,6775098,8923184,8923185,8923186,8923187,8923188,8923189,8923190,8923191,8923192,8923193,8923194,8923195,8923196,8923197,8923198,8923199,8923200,8923201,8923202,8923203,8923204,8923205,8923206,8923207,8923208,8923209,8923210,8923211,8923212,8923213,8923214,8923215,8923216,8923217,8923218,8923219,100124696,100187828,100505381,100506708,101926903);
+----------------+------------------+
| entrez_gene_id | hugo_gene_symbol |
+----------------+------------------+
|           3045 | HBD              |
|           4508 | ATP6             |
|           4509 | ATP8             |
|           4512 | COX1             |
|           4513 | COX2             |
|           4514 | COX3             |
|           4519 | CYTB             |
|           4535 | ND1              |
|           4536 | ND2              |
|           4537 | ND3              |
|           4538 | ND4              |
|           4539 | ND4L             |
|           4540 | ND5              |
|           4541 | ND6              |
|           4571 | TRNP             |
|           6421 | SFPQ             |
|           7006 | TEC              |
|          51072 | MEMO1            |
|         221938 | MMD2             |
|         654780 | SFPQ             |
|        6775063 | ND6              |
|        6775065 | CYTB             |
|        6775066 | ND5              |
|        6775071 | ND4L             |
|        6775072 | ND4              |
|        6775073 | COX3             |
|        6775074 | ATP6             |
|        6775076 | ND3              |
|        6775077 | ATP8             |
|        6775079 | COX2             |
|        6775083 | COX1             |
|        6775094 | ND2              |
|        6775098 | ND1              |
|      100124696 | TEC              |
|      100187828 | HBD              |
|      100505381 | MMD2             |
+----------------+------------------+
36 rows in set (0.01 sec)
</pre>
Similar to the events found from cna_event, there are clashing profiles here for:
- entrez 7006, and for entrez 100124696 .. both having name "TEC".
- entrez 3045, and for entrez 100187828 .. both having name "HBD".
There are also these other clashes:
- entrez 4508, and for entez 6775074 .. both having name ATP6
- entrez 4509, and for entez 6775077 .. both having name ATP8
- entrez 4512, and for entez 6775083 .. both having name COX1
- entrez 4513, and for entez 6775079 .. both having name COX2
- entrez 4514, and for entez 6775073 .. both having name COX3
- entrez 4519, and for entez 6775065 .. both having name CYTB
- entrez 100187828, and for entez 3045 .. both having name HBD
- entrez 100505381, and for entez 221938 .. both having name MMD2
- entrez 4535, and for entez 6775098 .. both having name ND1
- entrez 4536, and for entez 6775094 .. both having name ND2
- entrez 4537, and for entez 6775076 .. both having name ND3
- entrez 4538, and for entez 6775072 .. both having name ND4
- entrez 4539, and for entez 6775071 .. both having name ND4L
- entrez 4540, and for entez 6775066 .. both having name ND5
- entrez 4541, and for entez 6775063 .. both having name ND6
- entrez 6421, and for entez 654780 .. both having name SFPQ

Other notes:
- here MEMO1 only has events for the official gene (entrez 51072)

So for these events, we would need to decide whether the use of the unofficial entrez gene id was intended or was erroneous. If intended, then we need a proper way of disambiguating user queries for the ambiguous gene names (hugo gene symbol) to find the desired entrez gene id. (or at a minimum we could adopt a policy of "we cannot show this data currently" for all entrez genes with unofficial symbols, and filter this data out of display). We also need a way of showing the gene of an unofficial hugo symbol entrez gene in a way that distinguishes it from the official entrez gene. If not intended, then we need to merge/alter these records to the official/intended entrez id for these events.

**Comment by pieterlukasse** [comment]
@sheridancbio thanks for diving into this. One way to help users select the alternative gene in the user interface is to improve the disambiguation feature we currently have in the query page. For example, try entering MLL2 (see screenshot below)

image

We could make use of this feature by adding an alias for genes without an official symbol. The only issue now is that the feature above only works for genes that have an alias that is different from their official symbol. So having for example MMD2 as an official symbol of 221938 and as an alias of 100505381 is not yet seen as an ambiguous scenario by the UI and therefore the dropdown is not shown. Fixing this in the UI would be a big improvement and help solve this ambiguity problem. Regarding the data loading, all data loading should be done using the entrez id, which is the only safe way (i.e. rules like "the lowest entrez" will lead to errors).

**Comment by jjgao** [comment]
@pieterlukasse should we close this?

**Comment by Sjoerd-van-Hagen** [comment]
@pieterlukasse what should happen with this PR?

**Comment by sheridancbio** [comment]
Just to let people know that this is still on the radar, the  @cBioPortal/importer-pipelines  team has a (scrum) card in the product backlog for resolving issues with ambiguous gene symbols. It has not made it into our sprints, but we have discussed the issue from time to time. I think the consensus here was that want to keep entrez_id as the core identification for genes, and be able to support separate data profiles for distinct genes with the same gene symbol. My memory is that during the refactoring of the backend Web API we specified (at some point) that all api calls would make requests that reference genes by entrez_id. So I think the direction we preferred was to keep the gene table in sync with the download from NCBI and refactor our code to move away from linking to the table via gene symbol. (That's my somewhat fuzzy memory). But I'm sure we are open to discussing the issue more and considering alternatives.

**Comment by jjgao** [comment]
@sheridancbio is this still in your backlog?

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao @sheridancbio @pieterlukasse what should we do with this?

**Comment by jjgao** [comment]
closing this since it's really out of date. Please create another PR when you start to work on it. @sheridancbio

**Pull request closed without merging**
