### PR TITLE
description for "type" in mutation_count

### PR DESCRIPTION
**Pull request by anthony-cros**
see [original PR](https://github.com/cBioPortal/cbioportal/pull/1570)

### CODE REVIEW

**Comment by sheridancbio** [comment]
getMutationsCounts argument "type" has gone from required to not-required. Checking code now to see if an appropriate default is provided.

**Comment by sheridancbio** [comment]
According to ApiService.java, there is logic which puts into the results hashmap an entry under key "count" or key "frequency" based on the value of this parameter. If the parameter is not supplied, no key will be assigned to the hashmap. It seems like this parameter should be required to me. (Otherwise, no counts are added to the elements retrieved from the repository) Is this a use case ? (return values without count attribute or frequency attribute)?

**Comment by sheridancbio** [comment]
Ah .. I see .. second commit returned parameter to required. ok

**Comment by sheridancbio** [comment]
type 'count' probably means absolute counts. type 'frequency" is probably incorrect terminology. Frequency typically means the average number occurrences per duration interval. I need to speculate as to the true meaning here ... I'm guessing the intention might be 'proportion', 'fraction', or 'prevalence' relative to the complete sample set.  But adjusting this terminology (along with the api description) should probably be a different pull request.

**Comment by sheridancbio** [comment]
Will merge .. but please use git rebase to squash these two commits into one, and to relocate the changes to the front of the hotfix head.

**Comment by anthony-cros** [comment]
I can't seem to rebase, I'll have to look into why on Monday!

**Comment by sheridancbio** [comment]
I am closing this PR ... the submitted change is being incorporated through PR #1607 which I will now merge. This was to assist with rebasing the change set to the head of hotfix

**Comment by anthony-cros** [comment]
Thanks, Robert!

**Pull request closed without merging**
