### PR TITLE
Add The Hyve to Visualize Your Data 

### PR DESCRIPTION
**Pull request by sandertan**
# What? Why?
Add The Hyve to 'Visualize Your Data'-page as discussed in e-mail with @Sjoerd-van-Hagen @pieterlukasse @ecerami @schultzn @jjgao 

Also add URL to The Hyve on 'About'-page and update Hyve cBioPortal team members.

screen shot 2017-08-24 at 11 49 46

### CODE REVIEW

**Comment by jjgao** [comment]
Looks good to me. @schultzn @ecerami any comments?

**Comment by ecerami** [comment]
Looks good to me.  tx

**Comment by schultzn** [comment]
I just had a minor comment earlier… No need for three bullets under commercial support, it should be a single bullet.

**Comment by sandertan** [comment]
Thanks for the feedback. I've modified it to one bullet as @schultzn suggested:

screen shot 2017-08-28 at 11 51 20

**Comment by schultzn** [comment]
Looks great!

**Pull request merged**
