### PR TITLE
added small note regarding localhost url used

### PR DESCRIPTION
**Pull request by pieterlukasse**
# What? Why?
Improved Keycloak related documentation page, clarifying when to use http vs https in URL.

### CODE REVIEW

**Comment by Sjoerd-van-Hagen** [comment]
@mandawilson could you quickly review this small change so we can this PR can be merged?

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao can we get this tiny PR merged?

**Comment by jjgao** [comment]
sure. @pieterlukasse could you update the pr?

**Comment by oplantalech** [comment]
@jj PR rebased.

**Pull request merged**
