### PR TITLE
Fix unit tests

### PR DESCRIPTION
**Pull request by fedde-s**
These are the unit test fixes by Pieter and myself, as discussed.

### CODE REVIEW

**Comment by morungos** [comment]
So it looks like there's now conflicts in `core/src/test/resources/meta_CNA.txt` and `core/src/test/resources/clinical_data.txt`, so a bit of a tweak is needed

**Comment by fedde-s** [comment]
@morungos as mentioned in the chat, I am re-rebasing to solve that. Please do not branch from this PR for now.

**Comment by fedde-s** [comment]
The conflicts should now be fixed, and all tests should succeed.

**Comment by ersinciftci** [comment]
Looks good to me.

**Comment by pieterlukasse** [comment]
@morungos : yeah, apparently the clinical_data.txt file was reused by different tests. I think it is best if the different tests use their own files. That's one fix we could still make in this PR.

**Comment by jjgao** [comment]
@fedde-s: is this pull ready to be merged? If so, could you label it?

**Comment by fedde-s** [comment]
I am not entirely sure if @morungus still wants to review it or
@pieterlukasse still wants to add to it. As far as I am concerned it is
ready, and the architecture_work chat is looking forward it being merged.

**Comment by jjgao** [comment]
@morungos, @pieterlukasse: please confirm. Thanks.

**Comment by morungos** [comment]
I'm happy if @ersinciftci is happy. And I think he is. So go for the merge :-)

**Comment by pieterlukasse** [comment]
indeed :+1:  The small improvement I mentioned can be done by @ersinciftci in his PR as well

**Pull request merged**
