### PR TITLE
Recent data loading fixes

### PR DESCRIPTION
**Pull request by pieterlukasse**
Two fixes in this PR:
1- Fixed a part of the code where backwards compatibility logic was resulting in (many) unnecessary warnings for "invalid" patient ids for some of the genetic profile files. The first 2 commits cover this, where the second commit improves the "study_0" example study to better test this part of the code. 
2- In the unfortunate event of a NullPointerException (should not occur, but a bug can introduce it...) the loader aborts with error message "null". The fix ensures a stack trace is printed in this case as well.

### CODE REVIEW

**Comment by pieterlukasse** [comment]
@priti88 : can you test on your side as well?

**Comment by priti88** [comment]
@pieterlukasse I tested . Everything looks good.

**Comment by pieterlukasse** [comment]
@n1zea144 can you please review this?

**Comment by aderidder** [comment]
I tested as well. Seems fine.

**Comment by pieterlukasse** [comment]
assigned it to @zheins now (after talking to @jjgao )

**Comment by zheins** [comment]
@pieterlukasse This looks good to me. I'm going to be making a subsequent PR to make a few other changes we need for data loading backwards compatibility on our end, and to address some other issues I found while testing this out. I'll ask you to review.

@jjgao Should be fine to merge.

**Comment by ecerami** [comment]
@jjgao:  since @zheins has reviewed, can you please go ahead and merge?

**Pull request merged**
