### PR TITLE
Validator: Move attributes from sample to patient level

### PR DESCRIPTION
**Pull request by sandertan**
# What? Why?
Fix https://github.com/cBioPortal/datahub/issues/51

This PR moves the following attributes in the Validator from sample to patient level:
- SERUM_PSA
- TUMOR_GRADE
- HISTOLOGY
- TUMOR_SITE
- KNOWN_MOLECULAR_CLASSIFIER

### CODE REVIEW

**Comment by jjgao** [comment]
`SERUM_PSA` should probably be patient attribute, but I am not sure about the rest.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao They all seem like sample attributes to me but @ritikakundra indicated they are patient attributes in cBioPortal/datahub#51

**Comment by jjgao** [comment]
@ritikakundra could you comment?

**Comment by jjgao** [comment]
@ritikakundra we may need to do some cleanup at some point about whether an attribute belongs to patient or sample.

@Sjoerd-van-Hagen @sandertan do you think it is necessary to validate all the attributes for whether it is a patient or sample attribute? Maybe we should only do it for a list of core attributes?

**Comment by sandertan** [comment]
@jjgao At the time, we found that some attributes (I guess you could call them 'core') are required to be in the right data format. https://github.com/cBioPortal/datahub/issues/51#issuecomment-312817005

@ritikakundra Is this still important for you? Can we close this, or do you want to merge it? Or do you want to add anything to this PR, like the attributes named here https://github.com/cBioPortal/datahub/issues/51#issuecomment-318999771.

**Comment by ritikakundra** [comment]
@jjgao The issue I created for this for not to hardcode the attribute type. This causes validation to fail when we get study specific values.

**Comment by jjgao** [comment]
I think it's a good idea not to hard code the types of these attributes. @sandertan could you do that?

**Comment by pieterlukasse** [comment]
@jjgao @sandertan I made a PR to improve awareness on the frontend side as well: https://github.com/cBioPortal/cbioportal-frontend/pull/987

**Comment by sandertan** [comment]
Closing this PR and creating a new one for clarity and new purpose.

**Pull request closed without merging**
