### PR TITLE
fixing #2406

### LINKED ISSUE #2406: Loading of CNA overview on Study View never finishes
When opening the Study overview of a study with CNA data the cna overview never finishes loading. There is a request to cna.json? which receives 500 with this exception:

    HTTP Status 500 - org.mskcc.cbio.portal.dao.DaoException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND ALTERATION IN (-2,2) AND SAMPLE_ID in ('2','3','4','5','6','7','8','9','10' at line 1

with root cause

    org.mskcc.cbio.portal.dao.DaoException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND ALTERATION IN (-2,2) AND SAMPLE_ID in ('2','3','4','5','6','7','8','9','10' at line 1
	org.mskcc.cbio.portal.dao.DaoCnaEvent.getCnaEvents(DaoCnaEvent.java:176)
	org.mskcc.cbio.portal.servlet.CnaJSON.processGetCnaRequest(CnaJSON.java:135)

Looking at the code that constructs the query (around line 153):

                    + " AND sample_cna_event.CNA_EVENT_ID=cna_event.CNA_EVENT_ID"
                    + (entrezGeneIds==null?"":" AND ENTREZ_GENE_ID IN(" + StringUtils.join(entrezGeneIds,",") + ")")
                    + " AND ALTERATION IN (" + StringUtils.join(cnaLevels,",") + ")"

if entrezGeneIds == null then we get ""+ StringUtils.join(entrezGeneIds,",") + ")") 
That is just the ")" that causes the syntax error

### PR DESCRIPTION
**Pull request by jjgao**
moving code in #2407 to fix #2406

### CODE REVIEW

**Comment by jjgao** [comment]
@pieterlukasse could you help review this code?

**Comment by pieterlukasse** [comment]
hi @jjgao, sorry for the late reply. I think this is basically dead code now. Maybe we can remove the method instead?

**Comment by jjgao** [comment]
@n1zea144 @sheridancbio is this code dead?

**Comment by n1zea144** [comment]
@jjgao Just checked - seems it was only used by CnaJSON.java, so it is dead.

**Pull request closed without merging**
