### PR TITLE
Update shell

### PR DESCRIPTION
**Pull request by brittanystoroz**
# What? Why?
This updates the header, navigation bar and footer to fix issue #1983. 

Changes proposed in this pull request:
- Removes the table-based layout for the header contents.
- Slightly updated fonts & paddings in cBioPortal logo
- Linked to cBioPortal logo to the index page so we can remove the 'Home' link from the navigation menu. This is a very common convention and reduces some redundancy.
- Moved the navigation to the right-hand side and made the links a little subtler, as they should not necessarily be the main focus of the header.
- Reduced the size of the institute-specific logos. (max-height: 35px) I'd really like to replace all of these logos with their respective favicons, to get some standardization for styling and allow them to be slightly smaller.
- Styled the login/logout text

# Checks
- [x] Runs on Heroku.
- [x] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [x] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [x] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [x] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

# Screenshots
Header with institute logo & logged-in status:
loggedin-with-logo

Header with institute logo but no logged-in status:
notloggedin-with-logo

Header responsiveness at ~<1000px:
responsive

Footer:
footer

Full Homepage with new header & sidebars:
complete

# Some Notes/Questions for Reviewers:
The logged-in status/institute logo is still a bit larger than I'd like. Is there any way we could standardize these logos a bit? Some of them have white backgrounds, some are transparent, some have padding, some don't. I'd love to be able to use the favicons for each institute rather than the larger logos, or at least standardize transparency and padding issues. Essentially, I'd like each institute logo to be a little more predictable in terms of size and style. I'd be happy to do this standardization and replace each of the logo images if that's an option.

Are there any instances of cBioPortal where there is no institute logo and no login functionality? I know we mentioned we could remove the MSKC logo from the main instance, but for styling purposes, it is easier to keep it for now. (It might look nicer if we switch to just the logo image and drop the MSKC text in the logo.)

@cBioPortal/frontend

### CODE REVIEW

**Comment by brittanystoroz** [comment]
@ecerami @pieterlukasse Maybe you both would be good for taking a look at these styling updates as well? Thanks!

**Comment by zhx828** [comment]
@brittanystoroz this is awesome!! I really like the header design. What are your overall principles on designing new cBioPortal? Similar to Google's material design?

**Comment by brittanystoroz** [comment]
@jjgao @ecerami @pieterlukasse Would be nice to have this reviewed as well so we can get it merged along with the right sidebar changes!

@zhx828 Google's material UI --- and any stylistic framework for that matter --- is always a good foundation for design changes. My main design goals at the moment are consistency and simplicity. cbioportal already has a lot of complex data with an overwhelming amount of information. If we can de-emphasize the peripheral things (sidebars/headers/footers) by making them flatter and less obtrusive, users can pay more attention to the detail in the data.

**Comment by zhx828** [comment]
@brittanystoroz this is what I thought as well. Thanks for the information. I totally agree to make the pages cleaner by applying some material design concepts. Great work!

**Comment by jjgao** [comment]
@brittanystoroz could you please update the screenshot?

**Comment by brittanystoroz** [comment]
@jjgao I'm not sure how helpful these screenshot checks have been in the past, but unless they've been exceptionally useful I think we should consider removing them from the tests. Given the amount of time it takes to get a pull request through the review process, especially when doing design changes, it makes it difficult to keep the PR up-to-date and passing.

**Comment by jjgao** [comment]
@brittanystoroz they are useful for capturing errors. Before we have another end-to-end test solution, we still need them. In the future, before the final merge step, we can ignore the screenshot test error in the design stage.

I have created another pr from your branch and will fix the screenshots. Please don't worry about them.

**Comment by brittanystoroz** [comment]
@jjgao Awesome, thank you!

**Comment by jjgao** [comment]
merged: https://github.com/cBioPortal/cbioportal/pull/2189

**Comment by pieterlukasse** [comment]
@jjgao can we please merge this to rc as well? Looking forward to have this style in our project as well :+1:

**Pull request merged**
