### PR TITLE
news for release 3.0.0

### PR DESCRIPTION
**Pull request by jjgao**

### CODE REVIEW

**Comment by schultzn** [comment]
I don’t love the example .. will try to find a different one.

**Comment by schultzn** [comment]
How about the same example, but showing the mutations tab instead?
https://beta.cbioportal.org/comparison/mutations?sessionId=5cf89323e4b0ab413787436c <https://beta.cbioportal.org/comparison/mutations?sessionId=5cf89323e4b0ab413787436c>

And maybe also show a survival curve and clinical data comparison in the image?

**Comment by jjgao** [comment]
@schultzn I've change the screenshot to the mutations tab and also added another example for survival.

https://github.com/cBioPortal/cbioportal/blob/53454e04f59dc86980e0c1caf8d9daf2fd135866/docs/News.md

**Comment by tmazor** [comment]
@jjgao there's something weird happening in the second screenshot -- looks like the group button are missing text? It says "(ATMB..." but it's missing ")"

Other than that, looks good!

**Comment by jjgao** [comment]
updated: https://github.com/cBioPortal/cbioportal/blob/2c5854151760642e814b90f92ff061e1d0b6b8a9/docs/News.md

**Pull request merged**
