### PR TITLE
Query by Gene

### PR DESCRIPTION
**Pull request by aderidder**
Hi, 
This is the Query by Gene feature.
@zhx828 are you willing to review this, since you're the Study-view expert?

Thanks!

### CODE REVIEW

**Comment by zhx828** [comment]
@aderidder I'm starting to overview these code. I suggest we make some modification:
- [ ] Change gene qtip, position.my to center right and position.at to center left. In this way, the qtip won't be overlapped with gene in next row.
- [ ] Make the alert goes away after few seconds?

**Comment by zhx828** [comment]
screen shot 2015-12-01 at 4 06 42 pm

**Comment by zhx828** [comment]
screen shot 2015-12-01 at 4 07 37 pm

**Comment by zhx828** [comment]
screen shot 2015-12-01 at 4 08 17 pm

**Comment by zhx828** [comment]
The code seems ok to me

**Comment by aderidder** [comment]
Hi @HongxinZ, thanks for reviewing. I haven't a clue why the banners have
stopped going away; I'll look into it and fix it. Good suggestion about the
tooltip.

2015-12-01 23:29 GMT+01:00 HongxinZ <notifications@github.com>:

> The code seems ok to me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cBioPortal/cbioportal/pull/523#issuecomment-161116983>
> .
>



-- 
E.   sander@thehyve.nl
T.   +31(0)30 700 9713
W.  www.thehyve.nl

the hyve

**Comment by aderidder** [comment]
Hi @zhx828 
I did some digging and I traced the problem to ScatterPlot.js
In both appendAxisTitleX and appendAxisTitleY, there's a bit where the log checkbox is attached, e.g.
<code>
elem.axisTitleGroup.append("svg:foreignObject")
</code>
And part of this, is:
<code>
.append("xhtml:body")
</code>
If I remove these appends, the banner functionality works fine. The axis checkbox is also still working fine, although there is a slight change in the visual style.
Original:
image

Changed:
image

Would this be acceptable to you? Or do you perhaps know some other way around this problem? I am open to suggestions. Thanks!

**Comment by zhx828** [comment]
@aderidder I think the reason I added is because of the checkbox won't show up back to half year ago. If it doesn't have any issue and works for chrome and firefox, this is totally acceptable.

**Comment by aderidder** [comment]
hi @jjgao 
So, I hadn't fixed these issues yet, as I was more or less incapacitated last week. I'll aim to fix them today. Should I create a new pull request for the fix?

**Comment by jjgao** [comment]
@aderidder yes, please create a new pr to rc.

**Comment by jjgao** [comment]
@aderidder could you create an issue to log the issues?

**Pull request merged**
