### PR TITLE
Revert "Mutation data counts"

### PR DESCRIPTION
**Pull request by 7xuanlu**
Reverts cBioPortal/cbioportal#10559

### CODE REVIEW

**Comment by JREastonMarks** [comment]
@7xuanlu Can you expand more on why this is being reverted?

**Comment by 7xuanlu** [comment]
> @7xuanlu Can you expand more on why this is being reverted?

I was intended to do a rebase that can compress the commits a bit but decided not to do so

**Comment by inodb** [comment]
@7xuanlu could we maybe discuss this one at standup? I don't think I fully follow yet what you're trying to change

**Comment by qlu-cls** [comment]
Accidentally created this PR to revert https://github.com/cBioPortal/cbioportal/pull/10559.

**Pull request closed without merging**
