### PR TITLE
API to get gene(s) from hugo symbol(s)

### PR DESCRIPTION
**Pull request by JiaoJiao123**
# Why?
Currently there is no existed service to get gene from hugo symbol in the structure of Web Module -> Service Module -> Persistence Module. 

Changes proposed in this pull request:
- get gene list from hugo symbol list

This API followed the following structure: 
Web Module(Controller) -> Service Module(Service) -> Persistence Module(repository, mapper and mybatis xml implementation)

# Checks
This API can be accessed through the url below
api/geneListByHugoSymbols?hugoSymbols=BRAF,EGFR,KRAS

# Notify reviewers
@sheridancbio

### CODE REVIEW

**Comment by sheridancbio** [comment]
GeneMyBatisRepositoryTest uses setup file testContextDatabase.xml. I think we are moving away from .xml files towards java / annotation based configuration. If it is possible to transition this file as part of this PR, that would be good I think. But if it is a lot of work, we should probably do that kind of transition in another PR.

**Comment by sheridancbio** [comment]
- [ ] All files have placeholder license text. We should replace these with our standard 2016 copyright / license boilerplate.

**Comment by JiaoJiao123** [comment]
@sheridancbio could you show me one example of standard 2016 copyright / license boilerplate?

**Comment by sheridancbio** [comment]
Hi @JiaoJiao123 ... I think I have figured out what is causing the 404 not found error for the unit tests.  web/src/test/java/org/cbioportal/web/api/GeneControllerConfig.java is scanning for controllers in the places appropriate for the ApiController tests, but the MutationController and  GeneController are located in a different package.
   This line: @ComponentScan(basePackages = {"org.mskcc.cbio.portal.web.api", "org.mskcc.cbio.portal.persistence", "org.mskcc.cbio.portal.service"})
needs to add the package "org.cbioportal.web" in order for GeneController to be available during unit testing.

**Comment by sheridancbio** [comment]
The travis test may be failing because of this connection setting: -Ddb.connection_string=jdbc:mysql://127.0.0.1:3306/

In some recent (yesterday) updates to the rc branch, new database settings specify to use InnoDB engine by default. So if you rebase your code to the HEAD of rc, the travis checks should pass.

**Comment by JiaoJiao123** [comment]
ok, get it. I will open a new pr after I modified the end point.

**Pull request closed without merging**
