### PR TITLE
Updated PC network data & new SBGN view

### PR DESCRIPTION
**Pull request by istemi-bahceci**

### CODE REVIEW

**Comment by jjgao** [comment]
@istemi-bahceci would you please merge the latest rc code?

**Comment by istemi-bahceci** [comment]
@jjgao  Merged latest rc.

**Comment by jjgao** [comment]
@istemi-bahceci: you would need to run the migration code. https://github.com/cBioPortal/cbioportal/wiki/Updating-your-cBioPortal-installation

**Comment by jjgao** [comment]
I am merging this study and building a release candidate.

**Pull request merged**
