### PR TITLE
Global CSS Style update

### PR DESCRIPTION
**Pull request by pieterlukasse**
# What? Why?
Small update of Global .css style. 

Changes proposed in this pull request:
- remove the gradients from menu headers and footer
- increased the font of the menu. See screenshot below

image

# Notify reviewers
@jjgao

### CODE REVIEW

**Comment by pieterlukasse** [comment]
@jjgao let me know if this is OK, then I'll update the screenshot file to pass the end-to-end test

**Comment by jjgao** [comment]
@pieterlukasse I like it. Please updated the screenshots.

**Comment by jjgao** [comment]
@zhx828 could you help review the code?

**Comment by zhx828** [comment]
What do you think if we remove the 1px border? 
Before:
screen shot 2016-11-23 at 10 23 28 am

After:
screen shot 2016-11-23 at 10 23 47 am

**Comment by zhx828** [comment]
Other then the suggestion above, the code looks good to me. 👍

**Comment by jjgao** [comment]
@zhx828 @pieterlukasse good idea to remove the border.

**Comment by jjgao** [comment]
@schultzn @ecerami: what do you think about the new style?

https://cbioportal-pr-1913.herokuapp.com

**Comment by ecerami** [comment]
@pieterlukasse:  we have a new designer starting next week, and she is planning to revisit the global CSS.  Can we let her get started first?

**Comment by jjgao** [comment]
@ecerami: good idea to get her feedback on this.

**Comment by pieterlukasse** [comment]
@jjgao @ecerami thanks for the feedback. No pressure from my side, I was just sharing what we did for another project. If you have a designer that can look at this and make it even nicer, that is great 👍 

The changes I made here are really simple...and as such are not real changes. They basically just remove the gradient look.

**Comment by ecerami** [comment]
@pieterlukasse and @jjgao:  I am closing this PR as Brittany is now working on new CSS shell.

**Comment by jjgao** [comment]
I am reopenning this PR so that we can start a heroku instance. There was some discussion that @brittanystoroz started about this PR.

**Pull request closed without merging**
