### PR TITLE
Matchminer Proxy controller

### PR DESCRIPTION
**Pull request by victoria34**
# What? Why?
Create MatchMiner Controller as a proxy to get matched trials in patient view(Trial Match tab).

### CODE REVIEW

**Comment by zhx828** [comment]
@ersinciftci could you do a review on this PR? We added the proxy in the legacy code since this needs to attach a token for the requests. Please let us know if the structure needs to be updated. Thanks a lot.

**Comment by jjgao** [comment]
@victoria34 @zhx828 what's plan with this?

**Comment by zhx828** [comment]
@jjgao the hope is to get the frontend code reviewed and  decide which branch these changes should go. I almost done with my review, then it needs to be reviewed by Aaron.

**Comment by jjgao** [comment]
@zhx828 I think it's ok to push this code into master before the frontend code is reviewed as long as it's not breaking and it's small change.

**Comment by victoria34** [comment]
> @victoria34 @zhx828 what's plan with this?

Just got noticed. I'll rebase this branch now.

**Pull request closed without merging**
