### PR TITLE
Fix JaCoCo for multiprojects, now mvn site should work again. Resolve…

### LINKED ISSUE #1368: Maven site no longer works
The command

```
env PORTAL_HOME=`pwd` mvn -X clean compile test package
```

succeeds, but 

```
env PORTAL_HOME=`pwd` mvn -X clean compile test package site 
```

fails:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:site (default-site) on project master: failed to get report for org.apache.maven.plugins:maven-javadoc-plugin: Failed to execute goal on project core: Could not resolve dependencies for project org.mskcc.cbio:core:jar:1.3.0-SNAPSHOT: The following artifacts could not be resolved: org.mskcc.cbio:business:jar:1.3.0-SNAPSHOT, org.mskcc.cbio:service:jar:1.3.0-SNAPSHOT, org.mskcc.cbio:persistence-mybatis:jar:1.3.0-SNAPSHOT, org.mskcc.cbio:persistence-api:jar:1.3.0-SNAPSHOT, org.mskcc.cbio:model:jar:1.3.0-SNAPSHOT: Could not find artifact org.mskcc.cbio:business:jar:1.3.0-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:site (default-site) on project master: failed to get report for org.apache.maven.plugins:maven-javadoc-plugin
```

It's failing to resolve artifacts from modules, although this is definitely something that used to work. 

I'll see if I can get back to a working build and bisect

### PR DESCRIPTION
**Pull request by morungos**
# What? Why?

Fix #1368. Because maven site is totally broken

Changes proposed in this pull request:
- Bind JaCoCo so it runs after dependencies have been added to the Maven reactor
# Checks
- [ ] Runs on Heroku.
- [ ] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.
# Any screenshots or GIFs?

If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [GifGrabber](http://www.gifgrabber.com/).
# Notify reviewers

If your pull request involves changes to an existing file, one or more of the
people that edited before you might be good candidates to review it. Please use
`git blame <filename>` to determine that and notify them here. Otherwise notify
everybody in the core team:
@cBioPortal/core-developers

…s #1368.

See: http://stackoverflow.com/questions/23927329/jacoco-maven-plugin-causes-site-plugin-to-fail-in-multimodule-project

### CODE REVIEW

**Comment by inodb** [comment]
Seems to work for me

**Comment by sheridancbio** [comment]
I have not tried mvn "site", so I did not test any behavior here. My only comment about the change itself is that it is indented with an ascii tab character, which may cause indent inconsistencies across editors. But we have plenty of that already, so it is not a big problem.

**Comment by morungos** [comment]
Yes, there are some other site issues too. I don't have `dot`, for example, and I don't think it's right to assume its existence. I'm gonna move that into a profile.

**Comment by pieterlukasse** [comment]
I tested some of the changes here in combination with some extra settings I added to 2 pom files and it worked beautifully for the new API modules. See this commit for my changes: https://github.com/thehyve/cbioportal/commit/54b264ba5561294f6efb232639728dc0e78c51cb

Not sure if ALL these changes are needed, but at least this is a working version. Here some reports produced:

image

image

**Comment by pieterlukasse** [comment]
I fixed jacoco configuration here: #2389

**Comment by inodb** [comment]
This has been sorted in #2389

**Pull request closed without merging**
