### PR TITLE
Add parameter to remove What's New section

### PR DESCRIPTION
**Pull request by oplantalech**
Add boolean property in `portal.properties` to be able to remove the "What's New" section from the right bar. Associated frontend PR: https://github.com/cBioPortal/cbioportal-frontend/pull/1830

### CODE REVIEW

**Comment by oplantalech** [comment]
@sandertan I've added some documentation, in a new section called "cBioPortal customization". There are still some properties not explained in the document, and some which looks we're not using anymore (e.g. `skin.tag_line_image`) and some which might be worthy to rename for consistency. It would be good to take some time to review all properties to complete the documentation and propose removing the ones we're not using.

**Comment by alisman** [comment]
@oplantalech how come we cannot accomplish this by leaving what's new text blank?

**Comment by Sjoerd-van-Hagen** [comment]
@alisman Hi Aaron, can we get this merged?

**Comment by alisman** [comment]
@Sjoerd-van-Hagen sure.   we could merge this directly to master if you want.  if so, just change base of pr

**Comment by alisman** [comment]
@Sjoerd-van-Hagen actually, maybe we want to associate this with release number

**Comment by Sjoerd-van-Hagen** [comment]
@alisman Thanks!

**Pull request merged**
