### PR TITLE
Rearch Sprint 2 fixes

### PR DESCRIPTION
**Pull request by ersinciftci**
# What? Why?
Rearchitecture Sprint 2 fixes

# Checks
- [ ] Runs on Heroku.
- [ ] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

### CODE REVIEW

**Comment by sheridancbio** [comment]
Setting up for tests now

**Comment by jjgao** [comment]
merged per @ersinciftci's request.

**Comment by sheridancbio** [comment]
Testing was done on this PR (added to #1327), most problems were fixed during testing (before merge), but PR was merged with one outstanding issue.

**Comment by sheridancbio** [comment]
Tests performed were essentially the same tests as those for #1320 
However, mysql database matching as close as possible the production environment was used (mysql 5.1.72 / 5.1.73) with these adjustments to settings:
innodb_additional_mem_pool_size = 10485760
innodb_buffer_pool_size = 419430400
innodb_log_buffer_size = 8388608
innodb_log_file_size = 5242880
key_buffer_size = 16777216
max_allowed_packet = 268435456
max_connections = 10000
max_long_data_size = 268435456
net_buffer_length = 8192
open_files_limit = 500
read_buffer_size = 262144
read_rnd_buffer_size = 524288
sort_buffer_size = 524288
thread_cache_size = 0

The one outstanding issue was related to the setting group_concat_max_len. The default is 1024. The previous Dao code was setting this variable for the session as part of the mysql interaction. The workaround for testing was to alter the test mysql server by doing:
set global group_concat_max_len = 100000000;

This limit affects (truncates) lists of sampleIds returned as part of a mutsig counting query.

A followup PR will address this issue in code.

**Pull request merged**
