### PR TITLE
Separate System.exit calls from script functionality

### PR DESCRIPTION
**Pull request by fedde-s**
This is a proposal to solve issue #1113, by defining a superclass that implements `Runnable` to cleanly separate the the core functionality of the utilities in the `scripts` package from common logic specific to command line usage.

### CODE REVIEW

**Comment by morungos** [comment]
OK, this is still throwing a `System.exit()` but I think it's from inside `ConsoleUtil`. This is using an exit status of 2 to notify command syntax errors. My `TransactionalScriptRunner` is also doing this, and in more or less the same way. I think maybe we need a new class of `CommandSyntexException` thrown here, and used in `main` to call `System.exit`, and then refactor so nobody calls `main` from within Java. Would this work?

**Comment by morungos** [comment]
Don't know how to add to someone else's PR, but if you have a way you'd like for me to add to this, happy to do so. We need to get `rc` clean soon, and this is a useful part of it.

**Comment by morungos** [comment]
I think the VM exit is in `TestPanCancerStudySummaryImport` -- that would fit, as it's calling main methods.

**Comment by fedde-s** [comment]
Ah, thanks, I’d missed a System.exit(2) in ConsoleUtil, in a function that has a nearly identical name to a function I’d already adjusted. Also, I hadn’t adjusted the tests to call run() instead of main(String[]) yet, only made the run() methods and moved all (but one) of the System.exit()s to a separate shared method.

**Pull request merged**
