### PR TITLE
Move TUMOR_SITE to patient attributes

### PR DESCRIPTION
**Pull request by sandertan**
# What? Why?
Change the following attribute to be a PATIENT attribute instead of a SAMPLE attribute
- `TUMOR_SITE`

This was requested by @yichaoS to let several studies pass validation on CircleCI, such as `blca_tcga_pub_2017`, see:
https://384-63335718-gh.circle-artifacts.com/0/test-reports/ERRORS/blca_tcga_pub_2017-validation.html
I have **not** tested if the front end works as expected when these data types are in the clinical patient file.

Also, File-Formats is updated to reflect these changes. @jjgao @n1zea144 please comment if you agree with this data format.

### CODE REVIEW

**Comment by jjgao** [comment]
@yichaoS @ritikakundra Maybe we should not reuse the same attribute for both patient and sample b/c they may have different meanings and will create issues for cross-study analysis. If we need to use them in patients, should we just have different attributes, e.g. primary_site_patient?

**Comment by yichaoS** [comment]
@sandertan @jjgao @ritikakundra  Do we have examples of these attributes ever being used for patients?

**Comment by ritikakundra** [comment]
@sandertan only tumor_site needs to be changed to patient based. Rest all are sample level.

**Comment by sandertan** [comment]
@ritikakundra done.

**Comment by fedde-s** [comment]
New strict rules for some of these attributes from #3910 seem to have been included in the `release-1.15.0` branch. Should these amendments be included in that release as well, so that the release doesn't break compatibility with pre-existing studies?

**Comment by fedde-s** [comment]
Never mind! I see that it's already directed to `master`.

**Pull request merged**
