### PR TITLE
Network tab needs X-Frame-Options: SAMEORIGIN

### PR DESCRIPTION
**Pull request by inodb**
Better to handle this at app level instead of at server config level. Makes deployment easier

### CODE REVIEW

**Comment by alisman** [comment]
I'm confused now.  I thought we wanted to load the iframe html page from netlify (or from wherever we are hosting frontend).

**Comment by inodb** [comment]
@alisman this keeps behavior as it is currently, just moves the x frame headers from having to be set at nginx/Apache level to the app itself. We can discuss more tomorrow

**Comment by inodb** [comment]
Noticed it doesn't work when using social_auth, need to find a solution for that

**Comment by alisman** [comment]
maybe give the jsp an exception in web.xml?   ben recently made a PR for similar

**Comment by inodb** [comment]
Found it https://stackoverflow.com/questions/28647136/how-to-disable-x-frame-options-response-header-in-spring-security

**Pull request merged**
