### PR TITLE
Fix bug in heatmap legend

### PR DESCRIPTION
**Pull request by rnugraha**
Fix for issue #3146

Changes proposed in this pull request:
- Remove duplicated '%' sign when creating svg.stop

# Any screenshots or GIFs?
screen shot 2017-09-22 at 19 18 27

### CODE REVIEW

**Comment by fedde-s** [comment]
-3 in the heatmaps is supposed to be blue, while black signifies 0. Is this bug present in the code or is it just the screenshot?

**Comment by rnugraha** [comment]
@fedde-s hmm good finding. Another fix is just pushed, look at updated screen shot.

**Comment by jjgao** [comment]
@rnugraha could you please resolve the conflicts?

**Comment by rnugraha** [comment]
@JiaoJiao123 Just rebased it. Kindly pls check.

**Comment by jjgao** [comment]
@adamabeshouse I have merged it. Please make sure the changes are moved to the frontend repo.

**Pull request merged**
