### PR TITLE
submit button style relative to issue #828

### PR DESCRIPTION
**Pull request by JiaoJiao123**
Cause: submit button style was not specified, which made it editable as input element.
Fix: set type value to be submit and set width and height to adjust button size

### CODE REVIEW

**Comment by JiaoJiao123** [comment]
@schultzn @jjgao 
I specified the input type to be submit. It should be fine now.
Please check it out and let me know if any issue
https://cbioportal-pr-845.herokuapp.com/

**Comment by jjgao** [comment]
Looks good. Thanks, @JiaoJiao123! fixed #828

**Comment by zhx828** [comment]
The code looks good. But I would suggest to move the style into css file.

**Comment by JiaoJiao123** [comment]
@zhx828 Thanks for your suggestions! I moved the css style to the global_portal.css
https://cbioportal-pr-845.herokuapp.com/

**Comment by zhx828** [comment]
@JiaoJiao123 I would suggest to rename the class name with more specific meaning one. Current name may easily causes duplication issue since it is in global css.

**Comment by jjgao** [comment]
@JiaoJiao123 could you address this as well?

**Comment by JiaoJiao123** [comment]
@jjgao @zhx828 
class name changed to homePageSubmitButton

**Comment by zhx828** [comment]
@JiaoJiao123 there is no need to give the size. I've updated to Bootstrap button. Please see commit https://github.com/zhx828/cbioportal/commit/87c12454bf4683be9692d43cb979700d0eaa0115

**Comment by jjgao** [comment]
oops I merged it before see @zhx828's comments. @JiaoJiao123 could you create another pull?

**Comment by JiaoJiao123** [comment]
@zhx828 
so just use the bootstrap class style "btn btn-default btn-xs" for the submit button, and no need to write our own css at all right?

**Comment by JiaoJiao123** [comment]
@jjgao I will create another pull request

**Comment by zhx828** [comment]
@JiaoJiao123 yes. I already changed that in my merged pull request. You can just remove your newly styles and do a test.1

**Pull request merged**
