### PR TITLE
cBioSkins

### PR DESCRIPTION
**Pull request by aderidder**
This pull-request contains the cBioSkins features:

1. Set Right Logo
2. Turn on/off Tabs in Header Navigation Bar
3. Set News Blurb in the Right Column
4. Index Page Top Blurb
5. Footer
6. Customize Text within Login Page
7. Turn on / off Tabs within the Patient View
8. Adding a custom tabs

Default value in both portal.properties.EXAMPLE and GlobalProperties

### CODE REVIEW

**Comment by ecerami** [comment]
Any idea why this is failing the Travis CI build?  Is it due to code changes in the skins or due to config error in Travis CI?

**Comment by jjgao** [comment]
I also have a pull request failing the Travis build, but I didn't change anything related to Travis/Database/Unit tests. It seems that any pull requests from an branch older than the Travis-CI integration will break Travis. The same for Hongxin's new code.

**Comment by ecerami** [comment]
@aderidder, is this something you can look into for us, perhaps in consultation with gustavo?

**Comment by aderidder** [comment]
We've looked into the failed build problem which occurred. After some time we were able to reproduce it. The problem has to do with the encoding setting incompatibility. There are two ways to fix it:
1. Change the pom.xml in core, adding
<encoding>UTF-8</encoding>
<driverProperties>characterEncoding=utf8,
connectionCollation=utf8_general_ci
</driverProperties>

2. Change the my.cnf settings
It probably has:
character_set_server=utf8 
collation_server=utf8_unicode_ci 
If you comment these settings, it should also work.

Which would you prefer?

**Comment by ecerami** [comment]
I vote for option 1.  can you create a new pull request just for this change?  @jjgao can then merge into master (I think!)

**Comment by jjgao** [comment]
Sounds good.

**Comment by aderidder** [comment]
Ok I'll take care of it today

**Comment by inodb** [comment]
Has this been merged already in another PR or is this still ongoing?

**Pull request merged**
