### PR TITLE
Validator and loading improvements

### PR DESCRIPTION
**Pull request by pieterlukasse**
Hi @zheins : FYI here are the latest changes we made to the validator. We also started making some changes to the loader part, including moving the files to a new "importer" folder (so that all these python files are found together). Please use this updated code when adding a new validation. 

In the java part I also started cleaning up some of the unused code found in mutations importer.

### CODE REVIEW

**Comment by pieterlukasse** [comment]
Updated this pull request with most recent additions. Here some more details on this PR:
- new genesaliases API method
- extra validations
- changes to the loader code
- many unit tests
- DB schema improvements

**Comment by jochemb** [comment]
@pieterlukasse I like the validator, but I think it is too strict on clinical variables.  Specifically for things like the description and priority.  I think it would be great to have an option to be less strict these things and not throw and error, but only a warning.  Then the loading process should be changed so the definitions already in de database should be used.

**Comment by priti88** [comment]
@fedde-s There is a bug in the code. If my data mutation file does not have column Entrez gene ID, I get the following error:

Traceback (most recent call last):
  File "validateData.py", line 1943, in <module>
    logging.shutdown()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1666, in shutdown
    h.flush()
  File "/Users/priti/Documents/GIT/priti/cbioportal/core/src/main/scripts/importer/cbioportal_common.py", line 348, in flush
    record.getMessage())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1666, in shutdown
    h.flush()
  File "/Users/priti/Documents/GIT/priti/cbioportal/core/src/main/scripts/importer/cbioportal_common.py", line 348, in flush
    record.getMessage())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1666, in shutdown
    h.flush()
  File "/Users/priti/Documents/GIT/priti/cbioportal/core/src/main/scripts/importer/cbioportal_common.py", line 348, in flush
    record.getMessage())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

**Comment by fedde-s** [comment]
@priti88 Thanks, this does look like a bug. I'll look into it.

**Comment by fedde-s** [comment]
@priti88 It was a simple mistake, fixed in 885acb3b350d1264bc967a93ccd30eeab94e63c9. I already merged it into the hackathon-etl-team branch to which this pull request was merged.

**Pull request merged**
