### PR TITLE
Update FAQ.md

### PR DESCRIPTION
**Pull request by jjgao**
fixed https://github.com/cBioPortal/cbioportal/issues/4622

### CODE REVIEW

**Comment by jjgao** [comment]
@tmazor Thanks for the comments. I'll add a TOC. Sorry I missed your updates for formatting. Would you please point them out? Please also feel free to modify on top.

**Comment by jjgao** [comment]
@inodb any idea why e2e failed?

**Comment by inodb** [comment]
@jjgao aws dev dB got synced last Friday - had to rerun migration script. I just restarted the tests

**Comment by jjgao** [comment]
@inodb but I am pointing to master.

**Comment by inodb** [comment]
@jjgao fixed now. Yeah we did a partial migration so the same db works for both master n rc. At some point we really need to start importing test data as part of CI to avoid this

**Comment by tmazor** [comment]
@jjgao I made the formatting edits directly - there should be a commit from me from yesterday - but this is also the first time I've done that so maybe I messed something up?

**Comment by jjgao** [comment]
@tmazor you commit looks good 👍

FYI -- editing a pull request is actually the same as editing in the main repo - you are actually editing the file in my forked repo.

**Comment by jjgao** [comment]
@tmazor I added TOC: https://github.com/cBioPortal/cbioportal/blob/jjgao-patch-faq/docs/FAQ.md

Please note that it's a manual step so in the future we would need to manually add/change if we make changes to sections.

**Comment by jjgao** [comment]
@Tamba32 please review and approve if all look good and we can merge it.

**Pull request merged**
