### PR TITLE
Enable study view tests

### PR DESCRIPTION
**Pull request by zhx828**

### CODE REVIEW

**Comment by zhx828** [comment]
@inodb no sure what the issue is, the clinical data tab screenshot will not be compared https://travis-ci.org/cBioPortal/cbioportal/jobs/472798360

**Comment by inodb** [comment]
@zhx828 looks like it's fixed now right?

**Comment by zhx828** [comment]
@inodb yeah it seems working again.

**Comment by inodb** [comment]
We do study view e2e tests on the frontend now, so I think we can close this

**Comment by zhx828** [comment]
@inodb but don't you want to do some study view e2e tests on backend pr?

**Pull request closed without merging**
