### PR TITLE
Added compile version dependency management for compilation. Resolves…

### LINKED ISSUE #1505: Maven compile broken on OpenJDK7
The compile version isn't set in Maven, so it's defaulting to 1.3 under OpenJDK7.

Adding the following to the main `pom.xml` appears to fix it, by providing a default source versioning:

```
<build>
  ...
  <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>2.0.2</version>
          <configuration>
            <source>1.7</source>
            <target>1.7</target>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
</build>
```

### PR DESCRIPTION
**Pull request by morungos**
# What? Why?
Fix #1505 .

Changes proposed in this pull request:
- Added a compiler dependency management to default code to Java 7

# Checks
- [ ] Runs on Heroku.
- [ ] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [GifGrabber](http://www.gifgrabber.com/).

# Notify reviewers
If your pull request involves changes to an existing file, one or more of the
people that edited before you might be good candidates to review it. Please use
`git blame <filename>` to determine that and notify them here. Otherwise notify
everybody in the core team:
@cBioPortal/core-developers

… #1505

### CODE REVIEW

**Comment by pieterlukasse** [comment]
just out of curiosity: what was the problem? The previous one was working fine for me as of #1359

**Comment by morungos** [comment]
I was building on a Wheezy VM using OpenJDK7 and it was failing to compile the generics, saying that it needed source >1.3 for the new persistence components. Digging around, no source/target was set across all components. Only core seemed to be set to 1.7. This should do that.

**Comment by pieterlukasse** [comment]
ok...quite strange that different settings are needed in different environments. I guess that is why at some point this setting was widespread over different pom files in the project...

**Comment by morungos** [comment]
@pieterlukasse I think that was more because nobody knew how to do that in Maven. If you're running a Java8 you'll never see this issue, but it seems easy to reproduce on OpenJDK7 in particular. Just check out and compile.

**Comment by morungos** [comment]
FWIW this is what I'm doing here: https://maven.apache.org/pom.html#Plugin_Management

**Comment by pieterlukasse** [comment]
I tried it out and it works for me as well :+1: 

Let's merge this.

**Comment by morungos** [comment]
Well, it's failing the random unit tests again :-( -- this is the usual weird tests.

**Comment by pieterlukasse** [comment]
@morungos there is a rerun button in travis (I think you will get this once you login into travis)

image

**Pull request merged**
