### PR TITLE
Update OncoKB icon position

### PR DESCRIPTION
**Pull request by zhx828**

### CODE REVIEW

**Comment by zhx828** [comment]
This is the second part of fixing to solve issue https://github.com/cBioPortal/cbioportal/issues/2917 First part has been added in https://github.com/cBioPortal/cbioportal-frontend/pull/549. This pull request can be merged anytime after https://github.com/cBioPortal/cbioportal-frontend/pull/549 is approved.

**Comment by jjgao** [comment]
It seems the same?

image

**Comment by jjgao** [comment]
Is this ready to go?

**Comment by zhx828** [comment]
I think so.

**Pull request merged**
