### PR TITLE
Fix handling of OQL regulation direction

### LINKED ISSUE #1478: Expression data missing in rc oncoprint
Hi @adamabeshouse, it looks like oncoprint is broken in `rc` for expression data. Perhaps since #1416?

I fire the same query in my local environment (`rc`) and on cbioportal.org and in the `rc` version I don't get the expression data. See screenshots:

Query: http://www.cbioportal.org/index.do?cancer_study_list=brca_tcga&cancer_study_id=brca_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=brca_tcga_rna_seq_v2_mrna_median_Zscores&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_3way_complete&case_ids=&patient_case_select=sample&gene_set_choice=prostate-cancer%3A-ar-signaling-%2810-genes%29&gene_list=SOX9+RAN+TNK2+EP300+PXN+NCOA2+AR+NRIP1+NCOR1+NCOR2&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&

**master**
image

**rc**
image

**master (on my local env - for completeness)**
image

### PR DESCRIPTION
**Pull request by adamabeshouse**
# What? Why?
Fix #1478

# Checks
- [x] Runs on Heroku.
- [x] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [x] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [x] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

Changes proposed in this pull request:
Fix bug where mRNA and protein expression would not be displayed.
- Selectively annotate data with oql regulation direction during OQL filtering.
- Fix typo 'datum'->'event'

# Notify reviewers
@pieterlukasse @jjgao

### CODE REVIEW

**Comment by pieterlukasse** [comment]
I tested this fix and it works. I now see expression data again :+1: 

@jjgao will you do the code review? 

Side note: yesterday I got introduced to jasmine framework for unit testing (http://jasmine.github.io/) and I think we could apply this very well to some parts of our frontend code, especially the more recent ones like oncoprint. What do you think?

**Comment by pieterlukasse** [comment]
@adamabeshouse could you also add one or two tests regarding this in `test-oql-parser.js` ?

**Comment by adamabeshouse** [comment]
@pieterlukasse This isn't a parser-level change.

**Comment by pieterlukasse** [comment]
@adamabeshouse maybe an oncoprint screenshot test then? Could be another PR, I agree.

**Pull request merged**
