### PR TITLE
Fix styling updates

### LINKED ISSUE #2194: new styling issues
- [ ] `Data Sets` is selected in the home page. (maybe add a `Home` button)
 image
- [ ] The top buttons move to the left on: https://cbioportal-release-1-5-0.herokuapp.com/study?id=acc_tcga#summary.
- [ ] Remove MSKCC logo on top right.

### PR DESCRIPTION
**Pull request by brittanystoroz**
# What? Why?
Fixes #2194 

Changes proposed in this pull request:
- Fixes the automatic selection of the Data Sets link in the main nav bar. I have linked the cBioPortal logo to the home page so adding the 'Home' link in is unnecessary. I'd like to keep that link out of the nav to keep the header as uncluttered as possible.
- Fixes the study view links getting stuck to the left side and ensures the correct padding/margins exist on the logo.

@jjgao @inodb This should take care of all the issues with the updated styling. I set this PR to merge into release-1.5.0 but can change it to RC if needed, just let me know. Thanks!

# Checks
- [ ] Runs on Heroku.
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

### CODE REVIEW

**Comment by jjgao** [comment]
@brittanystoroz can we remove the msk logo?

**Comment by brittanystoroz** [comment]
@jjgao Yes! I was meaning to ask about that. If I remove the logic that includes the logo, it means that anyone's local logos would also be removed. Am I correct in assuming that we don't want to get rid of logos on *all* instances, and I should just remove the MSK logo property from the portal.properties file?

**Comment by jjgao** [comment]
@brittanystoroz good question. I think we only need to remove the logo in the public portal. So we can remove the logo by removing it from the properties file? If so, could you remove it from the example properties? 

Could you also update the screenshot if the pull request is ready?

Thanks!

**Comment by jjgao** [comment]
@brittanystoroz don't worry about the logo and screenshots. Since we are pushing out this Friday, I'll fix these things. Thanks for all your help.

**Comment by brittanystoroz** [comment]
I actually just did the logo logic and can update the screenshots momentarily.

**Comment by brittanystoroz** [comment]
The changes in the latest commit to remove the logo should still allow for local instances to define a specified logo with the `skin.right_logo` property. Wherever we are deploying the beta site and the main site, we need to remove that property and set the default_right_logo property to "".  (e.g. in my local copy I deleted `skin.right_logo` from any and all of the `.properties` files, and set the default logo property to an empty string.)

**Comment by jjgao** [comment]
Great. Thanks. @brittanystoroz

**Comment by brittanystoroz** [comment]
@jjgao Screenshots are updated and logo is removed (please see earlier comment about removing the `right_logo` value from the properties files in the deployed versions of the site)

**Pull request merged**
