### PR TITLE
User authorities are grouped by email and grouping is CASE SENSITIVE

### PR DESCRIPTION
**Pull request by mandawilson**
# What? Why?
Our users and authorities tables are set up to be case insensitive.  We can have one user in the authorities table with one email saved with different cases.  MyBatis does a **case sensitive** grouping on the user authorities email so one user in the database can be grouped into two separate sets of user authorities.  This was throwing an exception in MSK specific code.  Distinct users with emails of different cases in the authorities table can be found with this query:

	SELECT email, GROUP_CONCAT(DISTINCT case_sen_email), COUNT(DISTINCT case_sen_email) AS replicates
	FROM (SELECT CONVERT(email USING latin1) COLLATE latin1_bin AS case_sen_email, email FROM authorities) AS emails 
	GROUP BY email 
	HAVING replicates > 1;

Changes proposed in this pull request:
- Convert all emails to lower case in SELECT queries.

# Checks
- [ ] Runs on Heroku.
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). If you are part of the
cBioPortal organization, notify the approprate team (remove inappropriate):

@cBioPortal/backend

If you are not part of the cBioPortal organization look at who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them here:

### CODE REVIEW

**Comment by ersinciftci** [comment]
It seems H2 database supports `LOWER` function, so it won't be a problem when we start writing unit tests for security module.

**Comment by mandawilson** [comment]
@ersinciftci, @sheridancbio and I talked and we think the inserts should convert the email to lower case as well.  That is what core/src/main/scripts/importUsers.py does.  If we are worried about platforms not supporting SQL LOWER we could of course do this in a Java class instead.

**Comment by mandawilson** [comment]
I think the retrieval conversion should always be kept just in case someone manually adds authorities or introduces a third way of programmatically adding them.  As you say @sheridancbio it is not harmful and there is a low cost to it.

**Comment by mandawilson** [comment]
We should not merge this until we have also reviewed my changes to MSKCCPortalUserDetailsService.java (in MSK's Mercurial).

**Pull request merged**
