### PR TITLE
Partial scripts-based importer for structural variant datatype

### PR DESCRIPTION
**Pull request by sheridancbio**
Develop a scripts based import functionality for structural variant datatype

Changes proposed in this pull request:
- mybatis based table writing driven by core module java application importing
- unit tests and dataflow following similar recent efforts (gene-panel)

# Checks
- [ ] Runs on Heroku.
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

# Notify reviewers
@cBioPortal/backend

More details to be added to this description.

### CODE REVIEW

**Comment by jjgao** [comment]
@sheridancbio any update on this?

**Comment by jjgao** [comment]
@sheridancbio do we still need this pr?

**Comment by sheridancbio** [comment]
@jjgao We still need an import pipeline to be written for structural variants. I think that thehyve may have started working on this. If they have an active PR open, then this one is probably defunct. If not, this can be a reminder that the SV pipeline still needs to be written.

**Comment by jjgao** [comment]
I am closing this one since Hyve has been working on a new code for importing SV data.

**Comment by jjgao** [comment]
Please feel free to reopen if it's still relevant.

**Pull request closed without merging**
