### PR TITLE
Resolves #9011.

### LINKED ISSUE #9011: Structural Variant Genes Table does not show up for archer
https://cbioportal.mskcc.org/study/summary?id=mskarcher
Screen Shot 2021-10-28 at 11 48 20 AM

There is a SQL error:

```
### The error may exist in URL [jar:file:/target/tomcat.8888/webapps/expanded/WEB-INF/lib/persistence-mybatis-0-unknown-version-SNAPSHOT.jar!/org/cbioportal/persistence/mybatis/AlterationCountsMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT              ENTREZ_GENE_ID AS entrezGeneId,             HUGO_GENE_SYMBOL AS hugoGeneSymbol,             COUNT(*) AS totalCount,             COUNT(DISTINCT(CASE_ID)) AS numberOfAlteredCases         FROM         (                        ) as JoinedTable                    GROUP BY ENTREZ_GENE_ID, HUGO_GENE_SYMBOL;
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') as JoinedTable

        GROUP BY ENTREZ_GENE_ID, HUGO_GENE_SYMBOL' at line 9
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') as JoinedTable

        GROUP BY ENTREZ_GENE_ID, HUGO_GENE_SYMBOL' at line 9
```

### PR DESCRIPTION
**Pull request by n1zea144**
Fix #9011...to be confirmed by @ao508.  Tested against mskimpact, mskarcher, msk_impact_2017.

### CODE REVIEW

**Comment by ao508** [comment]
Testing to make sure the Oncoprint and patient/sample view Mutation Table still works with this fix also

**Review by ao508 — CHANGES_REQUESTED** [review]
Confirmed that the Structural Variant genes table renders correctly but the Oncoprint and Patient/Sample view mutation tables are broken now.

**Comment by ao508** [comment]
@n1zea144 seeing this error now when attempting to query by genes `BCR` and `ABL1`. Genes were chosen based on counts in Structural Variant genes table on study view. 

```
{"req":{"method":"POST","url":"//beta.cbioportal.mskcc.org/api/generic_assay_meta/fetch","data":{"genericAssayStableIds":[]},"headers":{"accept":"application/json","content-type":"application/json"}},"xhr":{},"text":"{\"message\":\"genericAssayStableIds size must be between 1 and 10000000\"}","statusText":"","statusCode":400,"status":400,"statusType":4,"info":false,"ok":false,"redirect":false,"clientError":true,"serverError":false,"error":{"status":400,"method":"POST","url":"//beta.cbioportal.mskcc.org/api/generic_assay_meta/fetch"},"created":false,"accepted":false,"noContent":false,"badRequest":true,"unauthorized":false,"notAcceptable":false,"forbidden":false,"notFound":false,"unprocessableEntity":false,"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"total-count,sample-count","cache-control":"no-cache, no-store, max-age=0, must-revalidate","connection":"keep-alive","content-length":"71","content-type":"application/json","date":"Mon, 01 Nov 2021 19:12:32 GMT","expires":"0","pragma":"no-cache","strict-transport-security":"max-age=0","x-content-type-options":"nosniff","x-frame-options":"DENY","x-xss-protection":"1; mode=block"},"header":{"access-control-allow-origin":"*","access-control-expose-headers":"total-count,sample-count","cache-control":"no-cache, no-store, max-age=0, must-revalidate","connection":"keep-alive","content-length":"71","content-type":"application/json","date":"Mon, 01 Nov 2021 19:12:32 GMT","expires":"0","pragma":"no-cache","strict-transport-security":"max-age=0","x-content-type-options":"nosniff","x-frame-options":"DENY","x-xss-protection":"1; mode=block"},"type":"application/json","links":{},"body":{"message":"genericAssayStableIds size must be between 1 and 10000000"},"url":"https://beta.cbioportal.mskcc.org/patient?studyId=mskarcher&caseId=P-0000012"}
```

**Comment by inodb** [comment]
Superseded by https://github.com/cBioPortal/cbioportal/pull/9027

**Pull request closed without merging**
