### PR TITLE
OncoKB updates; Bootstrap upgrade

### PR DESCRIPTION
**Pull request by zhx828**
Upgrade Bootstrap library:
* The library has been updated to 3.3.6 Most of modules have been tested on Chrome, FireFox and IE 11;

OncoKB updates:
* Add google form for user feedback about annotation column
* Add clinical summary
* Relayout the tooltip
* Distinguish variants between unknown variants and VUS(unknown variants but have been investigated)
* Change OncoKB icon color schema  
  * Blue: Oncogenic/Likely oncogenic
  * Dark grey: Not oncogenic
  * Grey: VUS
  * Grey circle: Unknown variants

Bug fixes:
*  Fixed bug #741

### CODE REVIEW

**Comment by zhx828** [comment]
@onursumer @jjgao Could you please help me review the code?

**Comment by zhx828** [comment]
This pull requests also relate to #353

**Comment by jjgao** [comment]
@zhx828 please make the pull to rc. There are too much changes for hotfix. We are supposed to use the rc branch to build beta wars anyway.

**Comment by zhx828** [comment]
@jjgao No problem.

**Pull request closed without merging**
