### PR TITLE
Add gene panels

### PR DESCRIPTION
**Pull request by zheins**
Gene panels added to database, import script, api, and oncoprint.

### CODE REVIEW

**Comment by n1zea144** [comment]
I don't think we should roll gene panel data into the apiController class.  Can we put it back into a separate controller?  In fact, the apiController should probably be broken up (another discussion).

**Comment by jjgao** [comment]
+1 on break apiController. There's no reason to put all into one controller.

**Comment by jjgao** [comment]
@zheins could you add some sql to the migration code and increase the version to 1.2.0?

**Comment by adamabeshouse** [comment]
@zheins lgtm

@jjgao,@n1zea144: Why prefer more controllers/services? The controller just passes calls back to the service, which delegates to the relevant mapper.

**Comment by jjgao** [comment]
@zheins @n1zea144 Let's push this forward and release it in 1.2.0.

**Comment by jjgao** [comment]
@zheins what's left on this pull request?

**Comment by zheins** [comment]
@jjgao, nothing. I'd just have to resolve the conflicts I think.

**Comment by jjgao** [comment]
@zheins when merging, could you increase the db version to 1.2.2?

**Comment by zheins** [comment]
@jjgao this PR now breaks the oncoprint. Since Adams new implementation was merged in, the gene panel information isn't being handled in the proper manner. I'll try to get this done by the end of the week.

**Comment by zheins** [comment]
Closing this for now unmerged - new pull request for the api, db schema, and import: https://github.com/cBioPortal/cbioportal/pull/1194

**Pull request closed without merging**
