### PR TITLE
Update Public-datasets.md

### PR DESCRIPTION
**Pull request by zheins**
# What? Why?
Fixes Issue #1637 
Update the documentation for public available datasets to point to datahub.

# Notify reviewers
@fedde-s

### CODE REVIEW

**Comment by zheins** [comment]
Potentially moving the tcga tarballs, need to wait for datahub pr to be reviewed and merged

**Comment by jjgao** [comment]
Do we need to list all of them here? Maybe just point to datahub is enough so that we don't have to update this page for every datahub release.

**Comment by fedde-s** [comment]
@jjgao: sounds good! And then maybe we can even find some other place for that link, such as at the end of the steps to get a portal installation up and running. But if not, we can just keep this ‘Public datasets’ page with a one-sentence paragraph that links to the datahub.

**Comment by jjgao** [comment]
superseded by @1650

**Pull request closed without merging**
