### PR TITLE
Replace dataTable with react table in study view  clinical tab - DO NOT MERGE

### PR DESCRIPTION
**Pull request by zhx828**

### CODE REVIEW

**Comment by zhx828** [comment]
This is for testing purpose at this moment. Please refer to #695 for more information.

**Comment by jjgao** [comment]
@zhx828 you may want to deploy a heroku instance so that we can test.

**Comment by zhx828** [comment]
@jjgao @pieterlukasse please see here https://intense-bastion-9218.herokuapp.com/

**Comment by pieterlukasse** [comment]
Nice!

**Pull request closed without merging**
