### PR TITLE
Fix to the DB_SCHEMA_VERSION setting in cgds.sql

### PR DESCRIPTION
**Pull request by sheridancbio**
In PR #1818 the DB_SCHEMA_VERSION setting in cgds.sql should have been updated to 1.3.1, but it was not. (migration.sql and pom.xml were updated to 1.3.1, and the table schema were adjusted in cgds.sql)

This change fixes the DB_SCHEMA_VERSION to match (bringing cdgs.sql into sync with migration.sql for the rc branch.)

Also, the version number for rc is skewed upwards to 100.0.0
This is to help distinguish the database schema version from the cbioportal web application release version number. (these numbers should not be expected to match, so this avoids confusion and makes clear that there are two separate things being versioned (the web application itself, and the database version)

# Checks
- [ ] Runs on Heroku.
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). If you are part of the
cBioPortal organization, notify the approprate team (remove inappropriate):

@cBioPortal/backend

- migration.sql and pom.xml refer to 1.3.1, and cgds.sql reflects that schema
- 1.3.1 was used "reused" during adjustment PR#1850
- cgds.sql value had not been updated as it should have been in PR#1818 (was still 1.3.0)

### CODE REVIEW

**Comment by jjgao** [comment]
since the code will be 1.4.0, should we upgrade the database schema version to 1.4.0?

**Comment by sheridancbio** [comment]
I think it is confusing to try to "sync" the DB_SCHEMA_VERSION with the cbioportal release version. They will be continually drifting apart, since there is not a new schema at every public release, and sometimes we will go through several schema updates between public releases. So I would strongly recommend that we actually "skew" the database version number to make it clearly different than the portal codebase version number.

On Friday I hope to discuss a proposal to be more formal about changing the database schema version ... for instance, @angelicaochoa wanted to adjust the database schema in hotfix, but rc has its own changes to the database schema. These will need to be merged in the future, but to keep things clear, about what database is expected by what code base, and what historical database schemas we have released (clarity needed for migration.sql) I think we should always issue a new version number to the schema any time modification-to-schema code is merged to our managed branches (master, rc, hotfix). migration.sql in master should take old versions of the database through the history of the versions which were incorporated into master (perhaps skipping over development versions which were in rc or hotfix if these are not part of the history of master).

So I think at the next merge of rc or hotfix to master we should change to some new numbering which is clearly different -- like 7.1.0 or something, and then continue from there.

**Comment by jjgao** [comment]
@sheridancbio Agreed. Good idea to change to a different numbering, e.g. 3.14, 3.141, ... :)

**Comment by sheridancbio** [comment]
The DB_SCHEMA_VERSION is now skewed away from the range used for the cbioportal web application codebase. (the two should not be expected to match, and should not be compared to each other.) This skew makes it clear that there are two separate version identifiers : one for the database schema, and one for the web application build.

**Comment by sheridancbio** [comment]
DB_SCHEMA_VERSION is set to 3.0.0
Going forward, I will recommend that we either move away from the ordered incrementing (3.0.0 .. 3.0.1 .. 3.0.2 .. 3.1.0 ...) and switch to using checksums on cgds.sql, or that we increment the center number for rc schema adjustments (3.0.0 .. 3.1.0 .. 3.2.0 .. 3.3.0 ...) and increment the final number for hotfix schema adjustments (3.2.0 .. 3.2.1 .. 3.2.2). Doing it this way means we can continue to use migration.sql for updating as is .. but it means that we will need to "hand-apply" hotfix changes to in-development databases which have been advanced in version number without a merged hotfix update.

**Comment by jjgao** [comment]
@sheridancbio maybe we should start with a bigger number, e.g. 100.0.0? Or can we support db1.3.1?

**Comment by sheridancbio** [comment]
I have added a fix to migrate_db.py ... previously it was not ignoring sql-style comments. I have added code to skip over sql-style comments on their own line. (notification : @zheins )

**Comment by sheridancbio** [comment]
@jjgao I don't think we can break the #.#.# pattern without breaking migrate_db.py .. since it compares numbers to see if sections of migration.sql are higher or lower than the current database version. Maybe we should reconsider this incrementing approach. (We can talk at Friday meeting)

Also, the width of DB_SCHEMA_VERSION is limited to 8 characters currently.  I'm going to up that to 256 characters for the field width. I don't think we will be updating major numbers very often .. but who knows. Ok, I'll go with 100.0.0

**Comment by sheridancbio** [comment]
@n1zea144 argued that there is not a good case for skewing the version numbers and that we should allow the cbioportal build version number naturally drift away from the db_schema_version number. If we now increment the major version number of db_schema_version for incompatible changes to the schema, it will soon become clear that the numbers are distinct and so there is no need to artificially skew. I have altered the code in this PR to move to version number 1.4.0, but still to widen the field in the info table to varchar(24)

**Comment by sheridancbio** [comment]
Note : the fix to the migrate_db.py script in this PR is also present in #1807 .. when merging, the two should become one.

**Pull request merged**
