### PR TITLE
Initial debloating work, currently untested. See #948

### PR DESCRIPTION
**Pull request by morungos**
As commented elsewhere, this is just an initial cut and hasn't yet been tested as a deployed web application. However, the scripts jar file does seem to work OK, and is now a more reasonable size.

### CODE REVIEW

**Comment by morungos** [comment]
Here's where we are at: I can built a complete and sensible war that's only about 52Mb that runs, and has most of what we need as far as I can find. It actually feels very much faster than the original too, which makes sense, as we've slimmed down the classloading by not having huge jars for core and business. 

Mostly this is a Maven and build reorganization.

**Comment by jjgao** [comment]
@morungos thanks for all the pull requests. Could you find someone to review them?

**Comment by morungos** [comment]
Sure, will do. Some of them are ready, but I want to see this one into a production deployment at UHN first.

**Comment by n1zea144** [comment]
I think @onursumer may want to look at this - I thought there was something in annotator or liftover modules that required the shading.  Is this code still being used?

**Comment by morungos** [comment]
I still do some shading: I build a new scripts jar that is shaded. I just don't shade the core and business components directly, because their dependencies are pulled into the final war directly. If you unzip -l the final war, you'll see the core and business jars are huge, and contain most of the same classes in the jars in the war. In the new model, the core and business jars are tiny, but the new scripts component is much bigger. 

You can think of this is a baby step towards a more component-based structure.

**Comment by sheridancbio** [comment]
Giving my observations here before passing this on for testing.

**Comment by sheridancbio** [comment]
After a brief search on the shade plugin, it is used for constructing an "uber-jar" with renaming of subcomponents during packaging. My first thought is that since the plugin is in many pom files, we must be created many "uber-jars" .. perhaps one per module.

In this change, the shade plugin is removed from the business module, and these dependencies have been added: mybatis mybatis-spring spring-context spring-tx jackson-annotations
Shade had been excluding org.bouncycastle:bcprov-jdk15 (who comes up with these organization names?) ... so now it apparently will not be excluded [wonder if this could cause a clash]
Also, two resource transformations are dropped: META-INF/spring.handler, META-INF/spring.schemas

In core, dropped shade plugin as before. Added: log4j  slf4j-api  apache-log4j-extras  guice  mysql-connector-java  spring-jdbc  spring-security-core  spring-security-web  spring-security-openid  spring-security-saml2-core  spring-social-core  spring-social-security  spring-social-google  junit

**A new module is added: scripts**
Also, in the root pom, dependencies are moved into an element "DependencyManagement" with some changes. I am guessing these are now a superset of dependencies in the modules [not verified]

In the portal module, there was not shade plugin before, and it is still absent. Added dependencies: tomcat-catalina  spring-security-taglibs  spring-security-ldap  spring-security-openid  spring-security-saml2-core

A new bean ("accessControl") in applicationContext-security.xml calls org.mskcc.cbio.portal.util.SpringUtil.setAccessControl 

And a "classpath:" reference in web.xml is changed to a literal "/WEB-INF/classes/"
This may cause problems if some system configurations are intended to allow the user to drop applicationContext-security.xml into a root directory or somewhere else in the classpath to configure the  system security.

The new scripts module contains the shade plugin, configured as elsewhere, plus a dependency to the core module.

The web module did not have shade before, and it still does not have it. Two dependencies were added: spring-webmvc spring-web  (I wonder why these dependencies are added .. perhaps these libraries were being included before in the uber-jar, but now are local and not in the uber-jar)

**Comment by sheridancbio** [comment]
First testing attempt:
Built war file using my own portal.properties and applicationcontext files.
Failure to deploy in Tomcat [looks like a mixture of tomcat database resource settings and missing or out of version tomcat-servlet-api-7.0.68.jar]

 ... from catalina.out:
INFO: Deploying web application archive /Library/Tomcat/apache-tomcat-7.0.67/webapps/cbioportal.war
Apr 13, 2016 1:42:58 PM org.apache.catalina.loader.WebappClassLoaderBase validateJarFile
INFO: validateJarFile(/Library/Tomcat/Home/webapps/cbioportal/WEB-INF/lib/tomcat-servlet-api-7.0.68.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
Apr 13, 2016 1:42:58 PM org.apache.catalina.startup.ContextConfig parseWebXml
SEVERE: Parse error in application web.xml file at jndi:/localhost/cbioportal/WEB-INF/web.xml
org.xml.sax.SAXParseException; systemId: jndi:/localhost/cbioportal/WEB-INF/web.xml; lineNumber: 11; columnNumber: 22; Error at (11, 22) : org.apache.catalina.deploy.WebXml setSessionConfig
	at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:2705)
<30 lines of stracktrace dropped>
Caused by: java.lang.NoSuchMethodException: org.apache.catalina.deploy.WebXml setSessionConfig
	at org.apache.tomcat.util.IntrospectionUtils.callMethod1(IntrospectionUtils.java:849)
	at org.apache.tomcat.util.digester.SetNextRule.end(SetNextRule.java:201)
	at org.apache.tomcat.util.digester.Digester.endElement(Digester.java:1060)
Apr 13, 2016 1:42:58 PM org.apache.catalina.startup.ContextConfig parseWebXml
SEVERE: Occurred at line 11 column 22
Apr 13, 2016 1:42:58 PM org.apache.catalina.startup.ContextConfig configureStart
SEVERE: Marking this application unavailable due to previous error(s)
Apr 13, 2016 1:42:58 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Apr 13, 2016 1:42:58 PM org.apache.tomcat.util.modeler.Registry registerComponent
SEVERE: Null component Catalina:type=DataSource,context=/cbioportal,host=localhost,class=javax.sql.DataSource,name="jdbc/cgds_public"
Apr 13, 2016 1:42:58 PM org.apache.tomcat.util.modeler.Registry registerComponent
SEVERE: Null component Catalina:type=DataSource,context=/cbioportal,host=localhost,class=javax.sql.DataSource,name="jdbc/cgds_gdac"
Apr 13, 2016 1:42:58 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more components marked the context as not correctly configured
Apr 13, 2016 1:42:58 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/cbioportal] startup failed due to previous errors

**Comment by morungos** [comment]
@sheridancbio I'm woking on this a bit today. The additional dependencies in web are because some components were being embedded in the uberjars of other cBio components, and therefore weren't needed as direct dependencies of web. Which is nasty, because they actually are dependencies of web. This is the problem of shading, essentially multiple versions of a dependency can show up and conflict. If you throw everything in as a top-level dependency, it looks okay because the versions are consistent, but it's not a description of the actual code dependencies, so it's all a bit awful really. 

We: the tomcat issue: I'm testing with Jetty. What version of Tomcat are you using? There is actually a Tomcat dependency because we use the CORSFilter, but it could be twitchy about which version of Tomcat you use.

**Comment by sheridancbio** [comment]
Tomcat version: Apache Tomcat/7.0.67

**Comment by sheridancbio** [comment]
Also, I noticed on this page a message: "This branch is out-of-date with the base branch" Merge the latest changes from rc into this branch.

**Comment by sheridancbio** [comment]
Maybe if I bring in the latest from rc, it will help the testing

**Comment by sheridancbio** [comment]
I merged in the head of the rc branch from the upstream repository and redeployed. The error message pattern in catalina.out was the same.

**Comment by morungos** [comment]
Weird. The tomcat dependency is there in 98f6d55

**Comment by morungos** [comment]
I'm having a deja vu that this might be a multiple XML parser conflict issue. Maybe there are different XML parsers in the war and/or web container somehow

**Comment by morungos** [comment]
@sheridancbio Can you post the full catalina,out? or a clean one from a start. I think there might be clues upstream.

**Comment by morungos** [comment]
I'm suspicious this might be due to embedding Tomcat in the war so we get the CorsFilter, which might normally come from the container. The war contains the whole of Tomcat v7.0.68, and this makes me think there's a loading conflict between container and war. I don't really like having to do it this way anyway, because CorsFilter isn't really part of the application. And even if it was, we shouldn't be taking it from an entire container. it'd be better as a Spring thing, or independent. Interesting it wasn't an issue, probably it's fine if you don't use a different version of Tomcat

**Comment by sheridancbio** [comment]
[catalina_full_message.txt](https://github.com/cBioPortal/cbioportal/files/217802/catalina_full_message.txt)

**Comment by morungos** [comment]
OK, yes, it's the servlet-api from tomcat. We can exclude that as a dependency. I really don't like depending on Tomcat anyway. It'd be very much better to either (a) not do CORS here but in the container as an override, or (b) delegate dynamically. However, I think an exclude will probably just work.

**Comment by sheridancbio** [comment]
Here are the lines between the point of tomcat startup and the first attempt to deploy a war:
Apr 13, 2016 1:42:16 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /Library/Tomcat/apache-tomcat-7.0.67/webapps/ROOT
Apr 13, 2016 1:42:16 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /Library/Tomcat/apache-tomcat-7.0.67/webapps/ROOT has finished in 51 ms
Apr 13, 2016 1:42:16 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Apr 13, 2016 1:42:16 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8009"]
Apr 13, 2016 1:42:16 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 1172 ms

**Comment by morungos** [comment]
New commit added which might fix that issue. I'll test in Jetty here

**Comment by morungos** [comment]
No such luck. The dependency is still there :-(

**Comment by morungos** [comment]
Right. The issue is that `maven-war-plugin` doesn't really do exclusions the same way as anything else. You have to do that in plugin configuration. Good lesson. We can probably slim down some of the other stuff, like XML parsers, too. But that's for another day. 

@sheridancbio: try this one

**Comment by sheridancbio** [comment]
trying pull/build/deploy now

**Comment by sheridancbio** [comment]
Ok, the exception about missing tomcat-servlet-api-7.0.68.jar seems to be gone.
There is still errors parsing web.xml during setSessionConfig (see below) and missing components for the data resource configuration within Tomcat (jdbc/cgds_public and jdbc/cgds_gdac ... which are my local names for connections to two different local databases on my system)

Here is catalina summary:
Apr 13, 2016 4:33:27 PM org.apache.catalina.startup.HostConfig undeploy
INFO: Undeploying context [/cbioportal]
Apr 13, 2016 4:37:07 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /Library/Tomcat/apache-tomcat-7.0.67/webapps/cbioportal.war
Apr 13, 2016 4:37:08 PM org.apache.catalina.startup.ContextConfig parseWebXml
SEVERE: Parse error in application web.xml file at jndi:/localhost/cbioportal/WEB-INF/web.xml
org.xml.sax.SAXParseException; systemId: jndi:/localhost/cbioportal/WEB-INF/web.xml; lineNumber: 11; columnNumber: 22; Error at (11, 22) : org.apache.catalina.deploy.WebXml setSessionConfig
        at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:2705)
<skip 30 stracktrace lines>
Caused by: java.lang.NoSuchMethodException: org.apache.catalina.deploy.WebXml setSessionConfig
        at org.apache.tomcat.util.IntrospectionUtils.callMethod1(IntrospectionUtils.java:849)
        at org.apache.tomcat.util.digester.SetNextRule.end(SetNextRule.java:201)
        at org.apache.tomcat.util.digester.Digester.endElement(Digester.java:1060)
Apr 13, 2016 4:37:08 PM org.apache.catalina.startup.ContextConfig parseWebXml
SEVERE: Occurred at line 11 column 22
Apr 13, 2016 4:37:08 PM org.apache.catalina.startup.ContextConfig configureStart
SEVERE: Marking this application unavailable due to previous error(s)
Apr 13, 2016 4:37:08 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs
 during scanning can improve startup time and JSP compilation time.
Apr 13, 2016 4:37:08 PM org.apache.tomcat.util.modeler.Registry registerComponent
SEVERE: Null component Catalina:type=DataSource,context=/cbioportal,host=localhost,class=javax.sql.DataSource,name="jdbc/cgds_public"
Apr 13, 2016 4:37:08 PM org.apache.tomcat.util.modeler.Registry registerComponent
SEVERE: Null component Catalina:type=DataSource,context=/cbioportal,host=localhost,class=javax.sql.DataSource,name="jdbc/cgds_gdac"
Apr 13, 2016 4:37:08 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more components marked the context as not correctly configured
Apr 13, 2016 4:37:08 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/cbioportal] startup failed due to previous errors

**Comment by morungos** [comment]
Okay, I'll need to deploy a Tomcat and test this more directly. I'm fairly sure it's a duplicate class conflict, and that's one of the annoyances of Java deployment with wars, and one of the advantages of, e.g., Spring Boot. A jar doesn't have this problem. However, we here need a war anyway for now, so I need to make this work.

**Comment by inodb** [comment]
Superseded by #1517

**Pull request closed without merging**
