### PR TITLE
Added "skin.right_nav.show_whats_new" to config_service.jsp

### PR DESCRIPTION
**Pull request by ngocnn1104**
Added `skin.right_nav.show_whats_new` to `config_service.jsp` to control the display of "What's new" component in the front-end.

### CODE REVIEW

**Comment by oplantalech** [comment]
@jjgao Can you merge this PR?

**Comment by inodb** [comment]
Thank you @oplantalech and @ngocnn1104! Could you elaborate what the difference is with setting `skin.right_nav.whats_new_blurb` to empty and update the docs accordingly? I guess it currently shows the cBioPortal Twitter when `skin.right_nav.whats_new_blurb` is empty? Thanks!

**Comment by oplantalech** [comment]
@inodb Is it confusing in the documentation? Currently it states:

> Settings controlling the "What's New" blurb in the right navigation bar: you can add any HTML code here that you want to visualize. If the field is left empty, the Twitter timeline will be shown (as long as skin.right_nav.show_whats_new is true, otherwise this section will not be displayed).

So as you mentioned, if you leave `skin.right_nav.whats_new_blurb` empty, and `skin.right_nav.show_whats_new=true`, then the "What's new" blurb will show the Twitter timeline. If `skin.right_nav.show_whats_new=false`, the section will not be shown (regardless of the content of `skin.right_nav.whats_new_blurb`).

The problem that this PR fixes is that `skin.right_nav.show_whats_new=false` was still showing the "What's new" section.

**Comment by jjgao** [comment]
@inodb please feel free to merge once you approve.

**Comment by inodb** [comment]
@oplantalech thanks for elaborating!

**Pull request merged**
