### PR TITLE
Integrate gene panel data into oncoprint

### PR DESCRIPTION
**Pull request by adamabeshouse**
Integrate gene panel data into oncoprint so that we can mark if a sample isn't sequenced for the gene vs being unaltered in the gene.
# Checks
- [x] ~~Runs on Heroku.~~ Impossible to check, no gene panel data in Heroku instance
- [x] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [x] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [x] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [x] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.
# Any screenshots or GIFs?

image
# Notify reviewers

@schultzn @jjgao @n1zea144 @zheins 
@cBioPortal/frontend

### CODE REVIEW

**Comment by sheridancbio** [comment]
Good development ... looking forward to checking this out

**Comment by adamabeshouse** [comment]
Things to add:

- Sort by N/S
- Reflect N/S in download data
- Tooltip: "Gene Panel: <name>"

**Comment by jjgao** [comment]
@alisman could you help review the code of this pr?

**Comment by adamabeshouse** [comment]
@jjgao @n1zea144 @schultzn following our discussion earlier today, I have a few questions about what's still needed:
(1) The tooltip right now will just say the gene panel name if the sample is sequenced in that gene. Do we want to add any other information/a link-out anywhere?
(2) Should the gene panel name/any other information be reflected in the download data tab?
(3) Do we want to add an option for hiding samples which are unsequenced in all the selected genes? This wouldn't be very hard to implement.

**Comment by adamabeshouse** [comment]
@jjgao @n1zea144 How does this look? 
image

**Comment by jjgao** [comment]
@adamabeshouse could you resolve the conflict?

**Comment by adamabeshouse** [comment]
@jjgao It should be ready now.

**Comment by jjgao** [comment]
@adamabeshouse please resolve conflicts.

**Pull request merged**
