### PR TITLE
Changed the name of api from `api-legacy` to `api` for validator.

### PR DESCRIPTION
**Pull request by angelicaochoa**
# What? Why?
Call to `api-legacy` doesn't work anymore for validator because of switch to just `api`

Changes proposed in this pull request:
- a
- b

# Checks
- [ ] Runs on Heroku.
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [GifGrabber](http://www.gifgrabber.com/).

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). If you are part of the
cBioPortal organization, notify the approprate team (remove inappropriate):

@cBioPortal/frontend
@cBioPortal/backend
@cBioPortal/devops

If you are not part of the cBioPortal organization look at who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them here:

### CODE REVIEW

**Comment by zheins** [comment]
This looks fine to me.

**Comment by pieterlukasse** [comment]
hi @angelicaochoa , this actually breaks the validation script for -u option. See https://github.com/cBioPortal/cbioportal/pull/1710#issuecomment-251356273 and #1748

**Comment by pieterlukasse** [comment]
@zheins feel free to revert it and close #1748. But maybe you can check with @ersinciftci first to see if the new api suffices for what we need here.

**Comment by ersinciftci** [comment]
Honestly I didn't get what `Call to api-legacy doesn't work anymore for validator because of switch to just api` means. I'm the one changing it to `api-legacy` because I changed the context root of the current API from `api` to `api-legacy`. And I started implementing the new API just last week, so I'm sure the new API doesn't suffice what is needed yet. So why did we need this PR?

**Comment by onursumer** [comment]
@angelicaochoa @zheins I recently updated the default service url for `ClinicalDataProxy` in `MutationMapper`: https://github.com/cBioPortal/mutation-mapper/pull/56/files#diff-7ed5a1a54195687602d5f7bdffa5189cL43

Renaming `api-legacy` back to`api` would break `ClinicalDataProxy` and `MutationSummaryView`, since right now cbioportal mostly relies on the default configuration values of `MutationMapper`

**Comment by ersinciftci** [comment]
This is reverted back in #1750 , so no problem anymore.

**Pull request merged**
