### PR TITLE
Added section about configuring groups to Authorization documentation

### PR DESCRIPTION
**Pull request by pieterlukasse**
# What? Why?
Added *missing* section about configuring groups to Authorization documentation. 

Changes proposed in this pull request:
- added documentation that was previously missing for existing documentation

# Notify reviewers
@ecerami, @priti88

### CODE REVIEW

**Comment by jjgao** [comment]
@pieterlukasse could you please point hotfix for this one too?

**Comment by pieterlukasse** [comment]
moved to #1600

**Comment by pieterlukasse** [comment]
closed #1600 and reopened this one again.

**Comment by jjgao** [comment]
@pieterlukasse could you update this pr?

**Pull request merged**
