### PR TITLE
Vertical zooming and scrolling and minimap

### PR DESCRIPTION
**Pull request by adamabeshouse**
https://github.com/cBioPortal/cbioportal/issues/1680

Support vertical zooming and scrolling in the oncoprint, and add a minimap view with a viewport-representative rectangle which can be dragged and resized to adjust the zoom and scroll of the oncoprint.
# Checks
- [x] Runs on Heroku.
- [x] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [x] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [x] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [x] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.
# Screenshots

image

image
# Notify reviewers

@cBioPortal/frontend
@jjgao

### CODE REVIEW

**Comment by jjgao** [comment]
@adamabeshouse very nice implementation. Maybe you could move the horizontal zoom functionality to the thumbnail view?

**Comment by jjgao** [comment]
@adamabeshouse a few small suggestions.

- [ ] use a lighter boarder
- [ ] do not show the minimap by default; instead, put it as a button (maybe a zoom icon) in the menu.
- [ ] when clicking on the button, display the minimap in a small floating window, which can also be closed.
- [ ] use cookie to remember whether the the mini-map is displayed.
- [ ] move the zoom functionality to mini-map, using icons similar to network tab.
- [ ]  when zooming, the center of the view should not change.

**Comment by adamabeshouse** [comment]
@jjgao I've addressed all the changes you requested (except for the gmail scrolling, I spun that out into another issue).

**Comment by jjgao** [comment]
@adamabeshouse great job!

- [ ] Good idea to add an (x) to close the window. The color/texture looks good to me.
- [ ] Could you replace the zoom icon with [this](http://www.freeiconspng.com/uploads/zoom-png-4.png)
- [ ] Is it possible to use similar style to the network tab for the horizontal and vertal zooming bars: lighter boarder and round corner?
image
- [ ] The fit button is grayish -- could you make it darker?

**Comment by adamabeshouse** [comment]
@jjgao All done

**Comment by adamabeshouse** [comment]
I added track highlight on mouseover to help tell what gene you're looking at when it's zoomed way out.

image

**Comment by jjgao** [comment]
@adamabeshouse could you resolve the conflicts when you have chance?

**Comment by adamabeshouse** [comment]
@jjgao I just want to wait until the heatmap is merged before starting to merge this one.

**Comment by jjgao** [comment]
@adamabeshouse please resolve the conflicts now.

**Comment by adamabeshouse** [comment]
@jjgao done 👍

**Pull request merged**
