### PR TITLE
Active directory

### PR DESCRIPTION
**Pull request by juleskers**
Add initial Active Directory authentication support to cBio.

This is the basic spring configuration to allow cBio to log-in via Active Directory accounts.
It adds the relevant portal.properties settings, spring Config and makes minor changes to the CancerStudyPermissionEvaluator to enable alternative spring-security authentication-providers.
APP.NAME:permission filtering was made optional (portal.properties setting) so that existing AD-groups need not be prefixed with "CBIOPORTAL:" to make them work.

The first whitespace-fix is really only running the IntelliJ codeformatter on the file.
This fixes several odd indents and the mixed use of tab-indenting and space-indenting. The tabs-to-spaces is sadly enough to confuse the github comparator, which makes this diff look needlessly complex.
Local diffing tools like meld handle this better.

Still ToDo: update the login screen with username and password boxes, currently uses the auto-generated barebones spring-security password entry screen.

### CODE REVIEW

**Comment by juleskers** [comment]
I've updated my branch to also have a fancy login-screen, so I'm closing this PR and creating a new one for you.

**Comment by juleskers** [comment]
OK, still a github beginner; apparently newly-added commits get automatically added to existing pull-requests...
You learn something every day :-)

**Comment by holtgrewe** [comment]
Hi Jules,

I might have done something wrong, but I'm getting the following error when running cBioPortal from your patch. What might be going on here?

```
SEVERE: Exception starting filter springSecurityFilterChain
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'springSecurityFilterChain' is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:641)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1159)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:282)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:979)
	at org.springframework.web.filter.DelegatingFilterProxy.initDelegate(DelegatingFilterProxy.java:324)
	at org.springframework.web.filter.DelegatingFilterProxy.initFilterBean(DelegatingFilterProxy.java:235)
	at org.springframework.web.filter.GenericFilterBean.init(GenericFilterBean.java:199)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4854)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5546)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by juleskers** [comment]
Oh goody, Spring errors...
It seems Spring cannot initialise, because it cannot find a _unique_ definition of 'springSecurityFilterChain'.
The error message is a bit misleading, it can mean that either Spring found zero definitions of 'springSecurityFilterChain', or more than one so that it can't decide which one to take.


It's hard to debug this remotely, it seems your Spring configuration (the sum of the different applicationContext xmls) are different for you then they are for me.

I can only say that having a clean checkout of this branch works for me.
Steps I follow:
1) git checkout active-directory
2) modify core/pom.xml to have the correct cbio-settingskey
```xml
...
<configuration>
  <!-- username & password gets put in .m2/settings.xml -->
-   <settingsKey>settingsKey</settingsKey>
+   <settingsKey>cbio_test_at_jules</settingsKey>
    <driver>com.mysql.jdbc.Driver</driver>
    <url>jdbc:mysql://localhost:3306/cgds_test</url>
...
```

3) PORTAL_HOME=/path/to/this/checkout/
4) mvn package
5) copy generated target/cbioportal.war to tomcat/webapps


And a long shot:
I've gotten very comical Spring errors when my machine was behind a proxy.
Apparently Spring validates the XML files it loads from the xsi:schemaLocation; being behind a proxy blocked this, which caused all sorts of seemingly unrelated parsing errors.
[Setting the java proxy settings](https://stackoverflow.com/questions/120797/how-do-i-set-the-proxy-to-be-used-by-the-jvm) solved this.

**Comment by juleskers** [comment]
OK, we resolved the merge-conflict that had appeared.

I'd appreciate if you could accept this before it diverges again.
I don't feel like doing this 4-hour merge again next month ;-)

**Comment by n1zea144** [comment]
We just updated the code to support the case when we don't want public studies to be visible by a logged in user. The following property needs to be sent in portal.properties if you want your desired behavior:

always_show_study_group=public

**Comment by bengusty** [comment]
I've configured AD authentication in our installation of cBioPortal and am able to authenticate after logging in, but get a NullPointerException after the redirect to index.do. I've entered database records for the user per the [User Authorization](https://github.com/cBioPortal/cbioportal/wiki/User-Authorization) page, and configured the relevant properties in portal.properties.

Below is the log from catalina.out showing that authentication is happening.
```
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/j_spring_security_check'; against '/css/**'
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/j_spring_security_check'; against '/saml/css/**'
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/j_spring_security_check'; against '/images/**'
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/j_spring_security_check'; against '/saml/images/**'
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/j_spring_security_check'; against '/js/**'
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/j_spring_security_check'; against '/saml/js/**'
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/j_spring_security_check'; against '/gfx/**'
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/j_spring_security_check'; against '/saml/gfx/**'
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.FilterChainProxy - /j_spring_security_check at position 1 of 10 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.context.HttpSessionSecurityContextRepository - HttpSession returned null object for SPRING_SECURITY_CONTEXT
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.context.HttpSessionSecurityContextRepository - No SecurityContext was available from the HttpSession: org.apache.catalina.session.StandardSessionFacade@49ab4fe. A new one will be created.
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.FilterChainProxy - /j_spring_security_check at position 2 of 10 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.FilterChainProxy - /j_spring_security_check at position 3 of 10 in additional filter chain; firing Filter: 'LogoutFilter'
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.FilterChainProxy - /j_spring_security_check at position 4 of 10 in additional filter chain; firing Filter: 'UsernamePasswordAuthenticationFilter'
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter - Request is to process authentication
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.authentication.ProviderManager - Authentication attempt using org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider - Processing authentication request for user: user1
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.ldap.SpringSecurityLdapTemplate - Searching for entry under DN '', base = 'dc=mycompany,dc=net', filter = '(&(objectClass=user)(userPrincipalName={0}))'
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.ldap.SpringSecurityLdapTemplate - Found DN: cn=user1,ou=Users,ou=NIBR,ou=PH,ou=USCA,dc=NA,dc=mycompany,dc=net
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider - 'memberOf' attribute values: [cn=CHAMPUSER ... DC=NA,DC=mycompany,DC=net]
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.ldap.userdetails.LdapUserDetailsMapper - Mapping user details from context with DN: cn=user1,ou=Users,ou=NIBR,ou=PH,ou=USCA,dc=NA,dc=mycompany,dc=net
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter - Authentication success. Updating SecurityContextHolder to contain: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@1199b244: Principal: org.springframework.security.ldap.userdetails.LdapUserDetailsImpl@d8563052: ...
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.authentication.SavedRequestAwareAuthenticationSuccessHandler - Using default Url: /index.do
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.DefaultRedirectStrategy - Redirecting to '/cbioportal/index.do'
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.context.HttpSessionSecurityContextRepository - SecurityContext stored to HttpSession: 'org.springframework.security.core.context.SecurityContextImpl@1199b244: Authentication: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@1199b244: Principal: org.springframework.security.ldap.userdetails.LdapUserDetailsImpl@d8563052: Dn: cn=user1,ou=Users...
2015-10-14 07:54:58 [http-bio-8080-exec-3] DEBUG org.springframework.security.web.context.SecurityContextPersistenceFilter - SecurityContextHolder now cleared, as request processing completed
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/index.do'; against '/css/**'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/index.do'; against '/saml/css/**'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/index.do'; against '/images/**'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/index.do'; against '/saml/images/**'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/index.do'; against '/js/**'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/index.do'; against '/saml/js/**'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/index.do'; against '/gfx/**'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/index.do'; against '/saml/gfx/**'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.FilterChainProxy - /index.do at position 1 of 10 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.context.HttpSessionSecurityContextRepository - Obtained a valid SecurityContext from SPRING_SECURITY_CONTEXT: 'org.springframework.security.core.context.SecurityContextImpl@1199b244: Authentication: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@1199b244: Principal: org.springframework.security.ldap.userdetails.LdapUserDetailsImpl@d8563052: Dn: cn=user1,ou=Users ...
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.FilterChainProxy - /index.do at position 2 of 10 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.FilterChainProxy - /index.do at position 3 of 10 in additional filter chain; firing Filter: 'LogoutFilter'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.FilterChainProxy - /index.do at position 4 of 10 in additional filter chain; firing Filter: 'UsernamePasswordAuthenticationFilter'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.FilterChainProxy - /index.do at position 5 of 10 in additional filter chain; firing Filter: 'BasicAuthenticationFilter'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.FilterChainProxy - /index.do at position 6 of 10 in additional filter chain; firing Filter: 'RequestCacheAwareFilter'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.FilterChainProxy - /index.do at position 7 of 10 in additional filter chain; firing Filter: 'SecurityContextHolderAwareRequestFilter'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.FilterChainProxy - /index.do at position 8 of 10 in additional filter chain; firing Filter: 'AnonymousAuthenticationFilter'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.authentication.AnonymousAuthenticationFilter - SecurityContextHolder not populated with anonymous token, as it already contained: 'org.springframework.security.authentication.UsernamePasswordAuthenticationToken@1199b244: Principal: org.springframework.security.ldap.userdetails.LdapUserDetailsImpl@d8563052: Dn: cn=user1,ou=Users...
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.FilterChainProxy - /index.do at position 9 of 10 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.FilterChainProxy - /index.do at position 10 of 10 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/index.do'; against '/auth/*'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/index.do'; against '/favicon.ico'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/index.do'; against '/login.jsp*'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/index.do'; against '/webservice.do*'
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.access.intercept.FilterSecurityInterceptor - Secure object: FilterInvocation: URL: /index.do; Attributes: [isAuthenticated()]
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.access.intercept.FilterSecurityInterceptor - Previously Authenticated: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@1199b244: Principal: org.springframework.security.ldap.userdetails.LdapUserDetailsImpl@d8563052: ...
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.access.vote.AffirmativeBased - Voter: org.springframework.security.web.access.expression.WebExpressionVoter@1ee554f1, returned: 1
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.access.intercept.FilterSecurityInterceptor - Authorization successful
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.access.intercept.FilterSecurityInterceptor - RunAsManager did not change Authentication object
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.FilterChainProxy - /index.do reached end of additional filter chain; proceeding with original chain
2015-10-14 07:54:58 [http-bio-8080-exec-8] DEBUG org.springframework.security.web.context.SecurityContextPersistenceFilter - SecurityContextHolder now cleared, as request processing completed
```
But then when the query_builder servlet is invoked, a NullPointerException is thrown. 
```
Oct 14, 2015 7:54:58 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [query_builder] in context with path [/cbioportal] threw exception
java.lang.NullPointerException
        at org.mskcc.cbio.portal.servlet.QueryBuilder.doPost(QueryBuilder.java:198)
        at org.mskcc.cbio.portal.servlet.QueryBuilder.doGet(QueryBuilder.java:147)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.mskcc.cbio.portal.util.XssFilter.doFilter(XssFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:439)
        at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by tlangs** [comment]
I fixed the issue with the NullPointerException. I've never submitted or merged a change to a project before though. How would I go about doing that?

```xml
        <b:bean class="org.springframework.beans.factory.config.MethodInvokingFactoryBean">
            <b:property name="staticMethod" value="org.mskcc.cbio.portal.util.SpringUtil.setAccessControl"/>
            <b:property name="arguments">
                <b:list>
                    <b:ref bean="accessControl"/>
                </b:list>
            </b:property>
        </b:bean>
```
needs to be added to `<b:beans profile="ad">` `applicationContext-Security.xml`

**Comment by n1zea144** [comment]
Hi Trevyn,

If you have a forked (clone) of the cBioPortal git repos, you can submit a pull request from your fork/branch back to the cBioPortal.  Someone will respond from there.

Thanks!
B

**Pull request merged**
