### PR TITLE
Fix1135_v2

### PR DESCRIPTION
**Pull request by aderidder**
Added functionality that checks whether mRNA or rppa data is negative and if it is, it will assume the data is already in log-space, even if the data_format is continuous

### CODE REVIEW

**Comment by aderidder** [comment]
Issue #1135

**Comment by pieterlukasse** [comment]
@jjgao : can you help us with review?

**Comment by jjgao** [comment]
@aderidder @pieterlukasse Thanks for the fix. I'll review it.

**Comment by jjgao** [comment]
@aderidder could you merge the latest hotfix? Thanks.

**Comment by pieterlukasse** [comment]
@jjgao merged in hotfix again. Still have to run a test here. Can you test it on your side as well to see if this is the desired functionality?

**Comment by jjgao** [comment]
@pieterlukasse sorry, my mistake. I meant to merge it.

**Pull request merged**
