### PR TITLE
Add genetic profiles to list and fix DaoMutation calls

### PR DESCRIPTION
**Pull request by adamabeshouse**
Fixes bug introduced by https://github.com/cBioPortal/cbioportal/pull/3207/files

### CODE REVIEW

**Comment by adamabeshouse** [comment]
@oplantalech hm how did you test it? because from where I'm looking, the argument to hasDriverAnnotations and numTiers will be a comma separated list of studies, and the oncoprint is not crashing. 

Try running it after typing this in the console: ```localStorage.heroku = "cbioportal-frontend-pr-666"```

**Comment by oplantalech** [comment]
@adamabeshouse That's what I see:
screenshot

When I debug, I see that the `hasDriverAnnotations` is called twice, the first time with a list of the queried cancer ids, and the second one with a list containing `all`, which is causing the error.

**Comment by adamabeshouse** [comment]
okay thanks @oplantalech, when you get a chance could you please try it again with the latest commit, still with the heroku? I was able to reproduce the crash and it seems to me I have fixed it

**Comment by inodb** [comment]
Note that you might have to do hard refresh to get around caching of heroku (not sure how long frontend artifacts are stored)

**Comment by adamabeshouse** [comment]
that shouldnt be a problem since these changes are actually in the backend

**Comment by oplantalech** [comment]
@adamabeshouse I tried it once again and now the `hasDriverAnnotations` is not called with `all` as parameter, but with `""` (apart from the iteration with the correct list of cancer IDs). It might also be that we're just working with different Tomcat versions. I'm running Tomcat  8.5.16.

**Comment by adamabeshouse** [comment]
thanks to @inodb for setting up test database to test this

**Pull request merged**
