### PR TITLE
Convert cBioPortal consequence to OncoKB consequence when fetching annotation from OncoKB

### PR DESCRIPTION
**Pull request by zhx828**

### CODE REVIEW

**Comment by jjgao** [comment]
I still cannot see the change in OncoKBConnector.js. Please fix that.

**Comment by jjgao** [comment]
Just for discussion, should this mapping on the cBioPortal side or OncoKB side?

**Comment by zhx828** [comment]
@jjgao I've fixed that on feature branch on my folk repository

**Comment by zhx828** [comment]
Merge to #572

**Pull request closed without merging**
