### PR TITLE
Use display name to label graphs on study view

### PR DESCRIPTION
**Pull request by j-hudecek**
Only if display name is not defined or is blank fallback to using attribute id. Solves #538

### CODE REVIEW

**Comment by jjgao** [comment]
@inodb: could you review this PR?

**Comment by inodb** [comment]
Looks fine to me. It does change the study view quite a bit, since all the headers for the graphs now use the `display_name` instead of the `attr_id`. E.g.
screen shot 2015-12-02 at 1 15 56 pm
Is there a reason why you didn't use `display_name` before @zhx828 ?

**Comment by zhx828** [comment]
Probably made a mistake. It should use display_name instead.

**Comment by jjgao** [comment]
@zhx828 could you check if it looks good for the mskimpact study.

**Pull request merged**
