### PR TITLE
changed meta-file flag for ImportCopyNumberSegmentData

### PR DESCRIPTION
**Pull request by pieterlukasse**
small fix to make sure the import process via  cbioportalImporter.py is aligned with the requirement for a meta file in the underlying java process (specific fix for ImportCopyNumberSegmentData)

### CODE REVIEW

**Comment by pieterlukasse** [comment]
fixes #178

**Comment by jjgao** [comment]
@zheins could you review the code?

**Comment by jjgao** [comment]
@pieterlukasse could you point this pr to rc?

**Comment by pieterlukasse** [comment]
@jjgao done

**Comment by jjgao** [comment]
merged #729 to rc.

**Pull request closed without merging**
