### PR TITLE
Load applicationContext-business.xml first

### LINKED ISSUE #5816: old issue back?
@n1zea144 we have a deployment where the exception mentioned here https://github.com/cBioPortal/cbioportal/pull/4611 : `Caused by: org.apache.ibatis.builder.IncompleteElementException: Could not find SQL statement to include with refid 'org.cbioportal.persistence.mybatis.PatientMapper.select'` 
shows up again when deploying v2.1.0. Any ideas what could be the cause?

### PR DESCRIPTION
**Pull request by oplantalech**
# What? Why?
Fix #5816.

### CODE REVIEW

**Comment by n1zea144** [comment]
@oplantalech Sorry, I've been away this week.  I've approved the PR.  Can you rebase and merge? Thanks!

**Comment by oplantalech** [comment]
@n1zea144 PR rebased. @jjgao can you merge it?

**Comment by pieterlukasse** [comment]
:+1: thanks @oplantalech and @n1zea144! I am happy this is solved! However, it also feels a bit fragile. Would be great to have /business legacy part removed altogether from the code in the near future.

@n1zea144 maybe you can merge this one?

**Comment by inodb** [comment]
@pieterlukasse merged

**Pull request merged**
