### PR TITLE
javax dependency

### PR DESCRIPTION
**Pull request by dippindots**
introduce javax dependency

### CODE REVIEW

**Review by JREastonMarks — COMMENTED** [review]
I'm not 100% sure why this needed when we haven't had to bring it in yet.

**Comment by dippindots** [comment]
@JREastonMarks This is related to the issue we see on the M series chip laptop when running v6 `cbioportal-docker-compose`
CC: @alisman

**Comment by haynescd** [comment]
@dippindots How did you test this?

I propose just updating the deps in pom to be scoped to test 
org.testcontainers.mockserver
org.mock-server.mockserver-client-java

**Comment by haynescd** [comment]
@alisman ok, awesome will do. I just don't think the mockserver should even be apart of the production build (which seems to be what pulls that need for the dep in)

This is all strange how its only on m1/m2 chips

**Pull request closed without merging**
