### PR TITLE
#397 Moved MethodInvokingFactoryBean to shared context

### PR DESCRIPTION
**Pull request by tlangs**
Moved to shared context so it could be used by all authentication providers. Less duplicate code this way.

### CODE REVIEW

**Comment by jjgao** [comment]
@tlangs thank you. Could you please click "update branch" button below?

**Comment by tlangs** [comment]
Sorry about all the weird commits. I'm still a little new to git. Build passes now and the redundant code is removed.

**Comment by pieterlukasse** [comment]
Looks good to me, as commented on #397

**Comment by n1zea144** [comment]
@tlangs Can you update your branch with hotfix and then we can merge.  Thanks!

**Pull request merged**
