### PR TITLE
Bootstrap styling for data validator HTML output

### PR DESCRIPTION
**Pull request by fedde-s**
This gives the HTML reports of the import data validator a more consistent and accessible styling, by phasing out the mix of Bootstrap and jQuery-Mobile and focussing on Bootstrap.

### CODE REVIEW

**Comment by fedde-s** [comment]
screen shot 2016-04-19 at 10 15 13

**Comment by fedde-s** [comment]
screen shot 2016-04-19 at 11 14 39

**Comment by pieterlukasse** [comment]
As just agreed with @jjgao and @n1zea144 : @priti88 will test this. If all is OK, I will merge it since this only concerns a HTML template that is part of the new validator.

**Comment by priti88** [comment]
@pieterlukasse I tested the new HTML template. It looks good.
Thank you

**Pull request merged**
