### PR TITLE
Support of LDAP authentication

### PR DESCRIPTION
**Pull request by xmao**
Add LDAP authentication provider for cBioPortal and enable LDAP users to get the authorizations from cBioPortal database

### CODE REVIEW

**Comment by n1zea144** [comment]
Hi Xmao,

Thank you for this pull request.  I'm just catching up on integrating some of these pull requests.  Have you noticed that someone has a pull request for LDAP support prior to this pull request?

https://github.com/cBioPortal/cbioportal/pull/102

**Comment by xmao** [comment]
Hi n1zea144,

I did not see #102 until I finish #287. #287 uses a lightweight way to integrate LDAP by injecting a customized LdapAuthoritiesPopulator into LDAP Auth Provider, while #102 customizes LDAPUserDetailsContextMapper. Other parts of these two pull requests are similar.

**Comment by n1zea144** [comment]
I'm closing this pull request due to solution provided in (but thank you for submission):

[PR-1200](https://github.com/cBioPortal/cbioportal/pull/1200)

**Comment by xmao** [comment]
Thanks for letting me know. Glad to see cBioPortal support LDAP finally.

**Pull request closed without merging**
