### PR TITLE
Dockerfile ready

### PR DESCRIPTION
**Pull request by als2076**
# What? Why?

Fix # . Added Docker Image to RC

Changes proposed in this pull request:
- a Added Dockerfile 
- b Updated Docker documentation
# Checks
- [ ] Runs on Heroku.
- [ ] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [x] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.
# Any screenshots or GIFs?

If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [GifGrabber](http://www.gifgrabber.com/).
# Notify reviewers

If your pull request involves changes to an existing file, one or more of the
people that edited before you might be good candidates to review it. Please use
`git blame <filename>` to determine that and notify them here. Otherwise notify
everybody in the core team:
@cBioPortal/core-developers

### CODE REVIEW

**Comment by jjgao** [comment]
Any update on this?

**Comment by jjgao** [comment]
Guys, Any update? I know there are a few things that we are still debating, but maybe we should decide on one temporary solution and make it work then optimize later? Thanks.

**Comment by jjgao** [comment]
Can we try to list what's left before we can merge the pull request?

**Comment by alexsigaras** [comment]
@jjgao Docker integration and documentation is done and will be pushed later on today.

**Comment by jjgao** [comment]
@alexsigaras let me know once it's done. We need to find someone to test it out. Thanks.

**Comment by jjgao** [comment]
superseded by #2214

**Pull request closed without merging**
