### PR TITLE
cleanup old clustering functions

### PR DESCRIPTION
**Pull request by pieterlukasse**
# What? Why?
Small source documentation, pending from https://github.com/cBioPortal/cbioportal/pull/1998/files#r98996479

### CODE REVIEW

**Comment by pieterlukasse** [comment]
notify @alisman, @inodb . 
Should this file move to frontend repo?

**Comment by jjgao** [comment]
Are these files in the portal module still being used? @adamabeshouse

**Comment by adamabeshouse** [comment]
@jjgao @pieterlukasse this code is now in the oncoprint library https://github.com/cBioPortal/oncoprintjs/blob/master/src/js/workers/clustering-worker.js

**Comment by pieterlukasse** [comment]
OK, I changed this PR to cleanup the files.

**Comment by pieterlukasse** [comment]
@adamabeshouse maybe you can also cleanup the /cbioportal/portal/src/main/webapp/js/src/oncoprint/ folder?

**Comment by pieterlukasse** [comment]
@adamabeshouse I also made a PR to frontend to clean it up: https://github.com/cBioPortal/cbioportal-frontend/pull/2489

**Comment by pieterlukasse** [comment]
@adamabeshouse can we please cleanup the files here (so merge this PR)? Please notice I changed this PR to remove the files instead of changing them.

**Pull request merged**
