### PR TITLE
Make oncoprint default view configurable

### PR DESCRIPTION
**Pull request by kretep**
To be able to set the default view to 'sample'. The default view is still 'patient'.

### CODE REVIEW

**Comment by kretep** [comment]
@pieterlukasse please have a look

**Comment by pieterlukasse** [comment]
OK, the issue does not seem to be with the code here. @adamabeshouse : this is what I found:

image

You could use an alternative to log2, like here: http://stackoverflow.com/questions/27853445/alternative-for-math-log2

**Comment by adamabeshouse** [comment]
@pieterlukasse That's been fixed in hotfix https://github.com/cBioPortal/cbioportal/pull/2116

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao Could you merge this PR?

**Comment by jjgao** [comment]
@kretep could you resolve the conflicts?

**Pull request merged**
