### PR TITLE
Patient view page enhancement

### PR DESCRIPTION
**Pull request by angelicaochoa**
# What? Why?
Function `guessClinicalData` only performs a check on whether the data type is undefined or if the data is null, but doesn't handle other "null values", such as 
'NA', 'unknown', 'undefined', etc. Functions that call `guessClinicalData` then have to add checks for these other "null values". 

I added a function to help standardize how clinical data are determined to be null, empty, NA, etc. for the **displayed** clinical data **ONLY** (not the dropdown tables).

**BEFORE**
before

**AFTER**
after

Changes proposed in this pull request:
- a
- b

# Checks
- [ ] Runs on Heroku.
- [ ] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to
  hotfix.

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [GifGrabber](http://www.gifgrabber.com/).

# Notify reviewers
If your pull request involves changes to an existing file, one or more of the
people that edited before you might be good candidates to review it. Please use
`git blame <filename>` to determine that and notify them here. Otherwise notify
everybody in the core team:
@cBioPortal/core-developers

### CODE REVIEW

**Comment by inodb** [comment]
I've actually been working on moving the clinical attribute styling from JS to CSS: https://github.com/cBioPortal/cbioportal/pull/1015. I think for N/A NA we should add something to the `clean()` function in ClinicalAttributesUtil: https://github.com/cBioPortal/cbioportal/pull/1015/files#diff-8504785b87a4049db3deb7b4978ce641R12 which removes such values

**Comment by angelicaochoa** [comment]
@inodb awesome! Definitely should add NA, N/A, and variants of those that we run into

**Comment by inodb** [comment]
Cool! I will try to add this function to PR #1015 then. Let me know if you have other suggestions. What patient is this? Should be a good test case

**Comment by pieterlukasse** [comment]
@angelicaochoa FYI : the list of "standardized null" values can also be found at the enum `ImportClinicalData.MissingAttributeValues` (ImportClinicalData.java) and at `validateData.py` (class `ClinicalValidator`). If you find any new "null  values", please update these places as well.

**Comment by angelicaochoa** [comment]
no problem @pieterlukasse ! I'll get to those later today

**Pull request closed without merging**
