### PR TITLE
Add news pathwaymapper

### PR DESCRIPTION
**Pull request by inodb**
The pathways tab has been out for almost two weeks, this adds the news item

### CODE REVIEW

**Comment by ugurdogrusoz** [comment]
How about a little rewording like this:
"The pathways are pulled from https://www.pathwaymapper.org and shown in a read only view. One can edit these pathways in the PathwayMapper editor as well."
As it is people might think that they can actually add pathways of their own to the pathway list available in cBioPortal.

**Comment by inodb** [comment]
@ugurdogrusoz good point! Updated with a minor change to wording (removed `as well`)

Curious: what's the process for adding new pathways that would show up in cBioPortal?

**Comment by ugurdogrusoz** [comment]
@inodb Pathways in PathwayMapper were previously drawn and saved on **server side**. The PathwayMapper editor allows one to create and save pathways locally and upload them for use later but the cBioPortal edition (viewer) can currently only display these pre-defined pathways on server side. If we get a student accepted for GSoC, we should see how we can accommodate users to make use of their own pathways within cBioPortal as well.

**Comment by inodb** [comment]
Thanks @ugurdogrusoz !

**Pull request merged**
