### PR TITLE
Gene set query page, oncoprint, plots tab and coexpression tab

### PR DESCRIPTION
**Pull request by pieterlukasse**
# What? Why?
This is the "frontend" part of the #2399 PR.

:white_check_mark: Review information: all code (except for rebase/conflict related fixes) has been reviewed by a MSK reviewer, except small changes/fixes that were later added and squashed to the fist commit (https://github.com/thehyve/cbioportal/commit/bd4eb4bd7074660b911966bc3c09bd8016d0deac, e.g. https://github.com/thehyve/cbioportal/commit/f634c69ac2d083681c28353cec21715b93f144cb)

Changes proposed in this pull request: For details, please refer to the individual PRs:
#2164: Gene set frontend
#2186: Gene set oncoprint tracks
#2190: Gene set oncoprint track expansion

### CODE REVIEW

**Comment by pieterlukasse** [comment]
rebased to rc today

**Comment by fedde-s** [comment]
@pieterlukasse, running this seems to load an incompatible version of the query page that does not recognise gene set score profiles. Is there something wrong with my build, or is this pull request not supposed to hold the latest working version of the GSVA-enabled fork of cBioPortal running on <https://cbioportal.thehyve.net/cbioportal/>? And if it isn't, where can I find the right branch?

**Comment by pieterlukasse** [comment]
New gene set related development should go as a PR to this branch: https://github.com/thehyve/cbioportal/tree/geneset_fixes

**Comment by fedde-s** [comment]
Thanks! 👍

**Comment by jjgao** [comment]
closing this since it's already merged.

**Comment by fedde-s** [comment]
The functionality for the plots and co-expression tabs have not yet been ported to the new frontend.

**Comment by jjgao** [comment]
got it. Thanks. @fedde-s

**Comment by fedde-s** [comment]
This outdated pull request isn't the most polished way to publicly track that task, but that's the reason we've been keeping it open with a ‘do not merge’ tag.

**Comment by jjgao** [comment]
@fedde-s since we will not merge it. We could also close this PR and create an issue.

**Comment by pieterlukasse** [comment]
completely outdated now.

**Comment by fedde-s** [comment]
Indeed; a port of the functionality has been included into the new frontend via https://github.com/cBioPortal/cbioportal-frontend/pull/742, https://github.com/cBioPortal/cbioportal-frontend/pull/898 and https://github.com/cBioPortal/cbioportal-frontend/pull/981.

**Comment by fedde-s** [comment]
Oh, apparently that's still not true for all tabs of the results view, but the remaining work is better tracked elsewhere.

**Pull request closed without merging**
