### PR TITLE
Remove threshold on calculating significant mutation genes in legacy endpoint

### PR DESCRIPTION
**Pull request by zhx828**
The current threshold creates inconsistency across pages.
For instance, RYR2 in luad_tcga_pub is highly mutated, but since the algorithm is designed as # mutations / gene length which causes RYR2 ranked really low will eventually be trimmed off from the list. But on the other hand, OncoPrint is showing all genes.
This solves #3305

Signed-off-by: Hongxin Zhang <jackson.zhang.828@gmail.com>

# Notify reviewers
@cBioPortal/devops

### CODE REVIEW

**Comment by jjgao** [comment]
@zhx828 could you update the screenshot?

**Comment by zhx828** [comment]
@jjgao done.

**Comment by jjgao** [comment]
Looks like there are conflicts?

**Comment by zhx828** [comment]
@jjgao it was due to another pull request of mine got merged in. It should be good now.

**Comment by jjgao** [comment]
It's not consistent but sometimes I got the error below:

https://cbioportal-pr-3306.herokuapp.com/study?id=skcm_tcga#summary

image

**Comment by zhx828** [comment]
@inodb once the travis is passed, this pull request is ready to merge.

**Comment by pieterlukasse** [comment]
No performance issues for large studies like MSK Impact?

**Comment by zhx828** [comment]
It’s surprisingly not effecting large studies. We tried to combine few
large studies and go to the study view, looks promising. Only saw one issue
is the mutated gene tab since the table is generated by data table. I have
a ticket open to replace it with react table. Do you see any performance
issue?

Hongxin

**Pull request merged**
