### PR TITLE
Add 'profiled' field instead of 'wholeExomeSequenced' to Gene Panel D…

### PR DESCRIPTION
**Pull request by ersinciftci**
…ata API

### CODE REVIEW

**Comment by fedde-s** [comment]
This looks like it's written in a way that will break existing code and code currently waiting for review :(   But I guess that's intentional.

**Comment by fedde-s** [comment]
Although in that case, note that it's directed to the master branch.

**Comment by pieterlukasse** [comment]
Is this a fix to an existing bug? If not, maybe move it to `rc`?

**Comment by ersinciftci** [comment]
@jjgao asked for this change for https://github.com/cBioPortal/cbioportal/issues/4104

**Pull request merged**
